<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:definition="http://www.bonitasoft.org/ns/connector/definition/6.1" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_TjN0gK8zEeuSJd-ffsoCUg" name="FabricationBiere" author="David" bonitaVersion="7.12.1" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_TjN0ga8zEeuSJd-ffsoCUg" name="Brasserie">
      <elements xmi:type="process:Lane" xmi:id="_TjN0gq8zEeuSJd-ffsoCUg" name="Employee lane" actor="_TjN0m68zEeuSJd-ffsoCUg">
        <elements xmi:type="process:StartEvent" xmi:id="_TjN0g68zEeuSJd-ffsoCUg" name="Start" outgoing="_q6qksMR_EeuDrfIRDXGjmg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_TjN0hK8zEeuSJd-ffsoCUg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_TjN0ha8zEeuSJd-ffsoCUg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TjN0hq8zEeuSJd-ffsoCUg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_TjN0h68zEeuSJd-ffsoCUg" name="Vérification du matériel" outgoing="_r3oj0Li5EeuOct60VCUhnQ" incoming="_2C7o8MPXEeufrKYRtmlCKQ _rIzuYMR_EeuDrfIRDXGjmg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_TjN0iK8zEeuSJd-ffsoCUg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_TjN0ia8zEeuSJd-ffsoCUg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TjN0iq8zEeuSJd-ffsoCUg" name="" content="" returnTypeFixed="true"/>
          <data xmi:type="process:Data" xmi:id="_X95D0MPeEeufrKYRtmlCKQ" name="nomBieres" dataType="_TjN0sa8zEeuSJd-ffsoCUg">
            <defaultValue xmi:type="expression:Expression" xmi:id="_X95D0cPeEeufrKYRtmlCKQ" content=""/>
          </data>
          <operations xmi:type="expression:Operation" xmi:id="_sU_UE8PDEeufrKYRtmlCKQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_sU_UFMPDEeufrKYRtmlCKQ" name="brasserie" content="brasserie" type="TYPE_VARIABLE" returnType="com.company.model.Brasserie">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_sU_UFcPDEeufrKYRtmlCKQ" name="brasserie" dataType="_TjN0tK8zEeuSJd-ffsoCUg" className="com.company.model.Brasserie"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_sU_UFsPDEeufrKYRtmlCKQ" name="brasserieInput.isMaterielSterilise" content="brasserieInput?.isMaterielSterilise" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_sU_UF8PDEeufrKYRtmlCKQ" name="brasserieInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_sU_7IMPDEeufrKYRtmlCKQ" type="JAVA_METHOD" expression="setIsMaterielSterilise">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_TjN0i68zEeuSJd-ffsoCUg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_TjN0jK8zEeuSJd-ffsoCUg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_TjN0ja8zEeuSJd-ffsoCUg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_TjN0jq8zEeuSJd-ffsoCUg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_TjN0j68zEeuSJd-ffsoCUg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_TjN0kK8zEeuSJd-ffsoCUg">
            <targetForm xmi:type="expression:Expression" xmi:id="_ZRfSIMO8Eeu5jNNAa7IUcQ" name="verificationMaterielForm" content="5b720115-8f62-49fb-b81e-b1511cd4791b" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_TjN0kq8zEeuSJd-ffsoCUg">
            <inputs xmi:type="process:ContractInput" xmi:id="_sU_UEMPDEeufrKYRtmlCKQ" name="brasserieInput" type="COMPLEX" dataReference="brasserie" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_sU_UEcPDEeufrKYRtmlCKQ" name="isMaterielSterilise" type="BOOLEAN" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_sU_UEsPDEeufrKYRtmlCKQ" expression="brasserieInput?.isMaterielSterilise != null" errorMessage="isMaterielSterilise is mandatory for Brasserie" name="mandatory_brasserieInput_isMaterielSterilise">
              <inputNames>brasserieInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_TjN0k68zEeuSJd-ffsoCUg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_brycwLi4EeuOct60VCUhnQ" name="Séparation des grains de malt cuits " outgoing="_wtf0oLi7EeuOct60VCUhnQ" incoming="_lH3kEMPZEeufrKYRtmlCKQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_brycwri4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_brycwbi4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_brycw7i4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_brycxLi4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_brycxbi4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_brycxri4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_brycyLi4EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_brycx7i4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_2S9vsLi4EeuOct60VCUhnQ" name="Deuxième filtrage " outgoing="_4_F-wLi4EeuOct60VCUhnQ" incoming="_esKjYMPCEeufrKYRtmlCKQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2S-Wwbi4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2S-WwLi4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2S-Wwri4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_2S-Ww7i4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_2S-WxLi4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_2S-Wxbi4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_2S-Wx7i4EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_2S-Wxri4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_4_C7cLi4EeuOct60VCUhnQ" name="Refroidissement du moût  " outgoing="_9mfnsLi4EeuOct60VCUhnQ" incoming="_4_F-wLi4EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4_C7cri4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4_C7cbi4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4_C7c7i4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_4_DigLi4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_4_Digbi4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4_Digri4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_4_DihLi4EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_4_Dig7i4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_9maIILi4EeuOct60VCUhnQ" name="Ajout des levures " outgoing="_FwOAgLi8EeuOct60VCUhnQ" incoming="_9mfnsLi4EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_9maIIri4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_9maIIbi4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_9maII7i4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_9maIJLi4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_9maIJbi4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_9maIJri4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_9maIKLi4EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_9maIJ7i4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_EgIZALi5EeuOct60VCUhnQ" name="Mise en bouteille " outgoing="_pp8c4Li8EeuOct60VCUhnQ" incoming="_k4Q2kLi8EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_EgJAEbi5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_EgJAELi5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_EgJAEri5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_EgJAE7i5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_EgJAFLi5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_EgJAFbi5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_EgJAF7i5EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_EgJAFri5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_OiqN4Li5EeuOct60VCUhnQ" name="Apéro" incoming="_OiufULi5EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OiqN4ri5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OiqN4bi5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_OiqN47i5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_PsEQgLi6EeuOct60VCUhnQ" name="Stérilisation du matériel et des cuves " outgoing="_Lrn54Li6EeuOct60VCUhnQ" incoming="__BIkQLi5EeuOct60VCUhnQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pWUdori5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pWUdobi5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pWUdo7i5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pWUdpLi5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pWUdpbi5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_pWUdpri5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_pWUdqLi5EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_pWUdp7i5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_zA3mIMPXEeufrKYRtmlCKQ" name="Boundary Timer1" outgoing="_1jtWUMPXEeufrKYRtmlCKQ">
            <condition xmi:type="expression:Expression" xmi:id="_zSHHIMPXEeufrKYRtmlCKQ" name="00:00:10" content="10000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_PsE3k7i6EeuOct60VCUhnQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_AVkN0MPBEeum97Fokdr50Q" name="sterilisationMaterielCuveForm" content="7f000208-62db-4e91-a2e5-e70ee2036c44" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_PsE3kri6EeuOct60VCUhnQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_PsE3lbi6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_scOCILi6EeuOct60VCUhnQ" name="Concassage du malt " outgoing="_3GaT8Li6EeuOct60VCUhnQ" incoming="_scSTkLi6EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_scOCIri6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_scOCIbi6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_scOCI7i6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_scOCJLi6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_scOCJbi6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_scOCJri6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_scOCKLi6EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_scOCJ7i6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_3GXQoLi6EeuOct60VCUhnQ" name="Porte" outgoing="_4b45ILi6EeuOct60VCUhnQ _46cdYLi6EeuOct60VCUhnQ" incoming="_3GaT8Li6EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3GXQori6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3GXQobi6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3GXQo7i6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_4b110Li6EeuOct60VCUhnQ" name="Ajout de l'eau dans la cuve" outgoing="_aRrVEMPCEeufrKYRtmlCKQ" incoming="_4b45ILi6EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4b110ri6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4b110bi6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4b1107i6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_4b111Li6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_4b111bi6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4b111ri6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_4b112Li6EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_4b1117i6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_46YL8Li6EeuOct60VCUhnQ" name="Ajout du malt concassé dans une cuve" outgoing="_YTslcMPCEeufrKYRtmlCKQ" incoming="_46cdYLi6EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_46YzAbi6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_46YzALi6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_46YzAri6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_46YzA7i6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_46YzBLi6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_46YzBbi6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_46YzB7i6EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_46YzBri6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_GEzl4Li7EeuOct60VCUhnQ" name="Brassage en continu" outgoing="_UJqWgMPZEeufrKYRtmlCKQ" incoming="_apR8wMPCEeufrKYRtmlCKQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GE0M8Li7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GEzl4bi7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GE0M8bi7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_GE0M8ri7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_GE0M87i7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_GE0M9Li7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_GE0M9ri7EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_GE0M9bi7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_wtcKQLi7EeuOct60VCUhnQ" name="Porte1" outgoing="_xLBeILi7EeuOct60VCUhnQ _xwAagLi7EeuOct60VCUhnQ" incoming="_wtf0oLi7EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_wtcxUbi7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_wtcxULi7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_wtcxUri7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_xK-a0Li7EeuOct60VCUhnQ" name="Infusion/ajout du houblon amérisant " outgoing="_7sHeULi7EeuOct60VCUhnQ" incoming="_xLBeILi7EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xK-a0ri7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xK-a0bi7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xK-a07i7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_xK-a1Li7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_xK-a1bi7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xK-a1ri7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_xK-a2Li7EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_xK-a17i7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_xv9XMLi7EeuOct60VCUhnQ" name="Infusion/ajout du houblon aromatique " outgoing="_ccGlQMPCEeufrKYRtmlCKQ" incoming="_xwAagLi7EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xv9XMri7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xv9XMbi7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xv9XM7i7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_xv9XNLi7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_xv9XNbi7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xv9XNri7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_xv9XOLi7EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_xv9XN7i7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_FwJvELi8EeuOct60VCUhnQ" name="Brassage léger de 15 minutes " outgoing="_JtCbYLi8EeuOct60VCUhnQ" incoming="_FwOAgLi8EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_FwJvEri8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_FwJvEbi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_FwJvE7i8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_FwJvFLi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_FwJvFbi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_FwJvFri8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_FwKWILi8EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_FwJvF7i8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Js-J8Li8EeuOct60VCUhnQ" name="Fermentation haute, 15 à 20 degrés, d’une durée de 7 jours " outgoing="_SNFJ0Li8EeuOct60VCUhnQ" incoming="_JtCbYLi8EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Js-xAbi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Js-xALi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Js-xAri8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Js-xA7i8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Js-xBLi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Js-xBbi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Js-xB7i8EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Js-xBri8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_SNBfcLi8EeuOct60VCUhnQ" name="Mesure de la densité de la bière" outgoing="_V4u8MLi8EeuOct60VCUhnQ" incoming="_SNFJ0Li8EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SNBfcri8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SNBfcbi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SNBfc7i8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <data xmi:type="process:Data" xmi:id="_PSCFwMPEEeufrKYRtmlCKQ" name="randomResponse" dataType="_TjN0sa8zEeuSJd-ffsoCUg">
            <defaultValue xmi:type="expression:Expression" xmi:id="_PSCFwcPEEeufrKYRtmlCKQ" content=""/>
          </data>
          <connectors xmi:type="process:Connector" xmi:id="_bZJ5gMPNEeufrKYRtmlCKQ" name="Test" definitionId="rest-get" event="ON_ENTER" ignoreErrors="true" definitionVersion="1.1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_bZJ5gcPNEeufrKYRtmlCKQ" definitionId="rest-get" version="1.1.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5gsPNEeufrKYRtmlCKQ" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5g8PNEeufrKYRtmlCKQ" name="http://www.randomnumberapi.com/api/v1.0/random?min=1&amp;max=100&amp;count=1" content="http://www.randomnumberapi.com/api/v1.0/random?min=1&amp;max=100&amp;count=1" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5hMPNEeufrKYRtmlCKQ" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_bZJ5hcPNEeufrKYRtmlCKQ"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5hsPNEeufrKYRtmlCKQ" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_bZJ5h8PNEeufrKYRtmlCKQ"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5iMPNEeufrKYRtmlCKQ" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5icPNEeufrKYRtmlCKQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5isPNEeufrKYRtmlCKQ" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5i8PNEeufrKYRtmlCKQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5jMPNEeufrKYRtmlCKQ" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5jcPNEeufrKYRtmlCKQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5jsPNEeufrKYRtmlCKQ" key="trust_self_signed_certificate">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5j8PNEeufrKYRtmlCKQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5kMPNEeufrKYRtmlCKQ" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5kcPNEeufrKYRtmlCKQ" name="Strict" content="Strict" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5ksPNEeufrKYRtmlCKQ" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5k8PNEeufrKYRtmlCKQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5lMPNEeufrKYRtmlCKQ" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5lcPNEeufrKYRtmlCKQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5lsPNEeufrKYRtmlCKQ" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5l8PNEeufrKYRtmlCKQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5mMPNEeufrKYRtmlCKQ" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5mcPNEeufrKYRtmlCKQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5msPNEeufrKYRtmlCKQ" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5m8PNEeufrKYRtmlCKQ" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5nMPNEeufrKYRtmlCKQ" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5ncPNEeufrKYRtmlCKQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5nsPNEeufrKYRtmlCKQ" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5n8PNEeufrKYRtmlCKQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5oMPNEeufrKYRtmlCKQ" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5ocPNEeufrKYRtmlCKQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5osPNEeufrKYRtmlCKQ" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5o8PNEeufrKYRtmlCKQ" name="-1" content="-1" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5pMPNEeufrKYRtmlCKQ" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5pcPNEeufrKYRtmlCKQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5psPNEeufrKYRtmlCKQ" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5p8PNEeufrKYRtmlCKQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5qMPNEeufrKYRtmlCKQ" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5qcPNEeufrKYRtmlCKQ" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5qsPNEeufrKYRtmlCKQ" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5q8PNEeufrKYRtmlCKQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5rMPNEeufrKYRtmlCKQ" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5rcPNEeufrKYRtmlCKQ" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5rsPNEeufrKYRtmlCKQ" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5r8PNEeufrKYRtmlCKQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5sMPNEeufrKYRtmlCKQ" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5scPNEeufrKYRtmlCKQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5ssPNEeufrKYRtmlCKQ" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5s8PNEeufrKYRtmlCKQ" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bZJ5tMPNEeufrKYRtmlCKQ" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_bZJ5tcPNEeufrKYRtmlCKQ" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_bZJ5tsPNEeufrKYRtmlCKQ">
              <leftOperand xmi:type="expression:Expression" xmi:id="_bZJ5t8PNEeufrKYRtmlCKQ" name="brasserie" content="brasserie" type="TYPE_VARIABLE" returnType="com.company.model.Brasserie">
                <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_bZJ5uMPNEeufrKYRtmlCKQ" name="brasserie" dataType="_TjN0tK8zEeuSJd-ffsoCUg" className="com.company.model.Brasserie"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_bZJ5ucPNEeufrKYRtmlCKQ" name="newScript()" content="import java.util.logging.Logger&#xD;&#xA;&#xD;&#xA;Logger log = Logger.getLogger(&quot;org.bonitasoft&quot;)&#xD;&#xA;String value = bodyAsString.replace(&quot;[&quot;, &quot;&quot;)&#xD;&#xA;value = value.replace(&quot;]&quot;, &quot;&quot;)&#xD;&#xA;log.severe(value)&#xD;&#xA;&#xD;&#xA;return Integer.valueOf(value)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
                <referencedElements xmi:type="definition:Output" xmi:id="_rvDUcMPOEeufrKYRtmlCKQ" name="bodyAsString" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_bZJ5u8PNEeufrKYRtmlCKQ" type="JAVA_METHOD" expression="setDensiteBiere">
                <inputTypes>java.lang.Integer</inputTypes>
              </operator>
            </outputs>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SNBfdLi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SNBfdbi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SNBfdri8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SNBfeLi8EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SNBfd7i8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndErrorEvent" xmi:id="_fG1qgLi8EeuOct60VCUhnQ" name="This is the end" incoming="_fHACkLi8EeuOct60VCUhnQ" errorCode="END">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_fG2Rkbi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_fG2RkLi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_fG2Rkri8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_pp5ZkLi8EeuOct60VCUhnQ" name="Encapsulage " outgoing="_p697cLi8EeuOct60VCUhnQ" incoming="_pp8c4Li8EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pp5Zkri8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pp5Zkbi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pp5Zk7i8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pp5ZlLi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pp5Zlbi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_pp5Zlri8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_pp5ZmLi8EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_pp5Zl7i8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_p66RELi8EeuOct60VCUhnQ" name="Etiquetage" outgoing="_vO4sILi8EeuOct60VCUhnQ" incoming="_p697cLi8EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_p664Ibi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_p664ILi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_p664Iri8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_p664I7i8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_p664JLi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_p664Jbi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_p664J7i8EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_p664Jri8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_40qTkLi8EeuOct60VCUhnQ" name="Vidange de la cuve" outgoing="_fHACkLi8EeuOct60VCUhnQ" incoming="_XKna0Li8EeuOct60VCUhnQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XKk-kbi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XKk-kLi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XKk-kri8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_XKk-k7i8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_XKk-lLi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_XKk-lbi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_XKk-l7i8EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_XKk-lri8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_40q6qbi8EeuOct60VCUhnQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_jGPz8MPAEeum97Fokdr50Q" name="vidangeCuveForm" content="245975d6-0630-40ad-b27c-8b2a0333a09a" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_40q6qLi8EeuOct60VCUhnQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_40q6q7i8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_6ZXLELi9EeuOct60VCUhnQ" name="Stockage des bouteilles durant 7 jours" outgoing="_OiufULi5EeuOct60VCUhnQ" incoming="_vO4sILi8EeuOct60VCUhnQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_F_Hfgri5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_F_Hfgbi5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_F_Hfg7i5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_y8ixsMPVEeufrKYRtmlCKQ" name="SendMail" definitionId="email" event="ON_FINISH" ignoreErrors="true" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_y8ixscPVEeufrKYRtmlCKQ" definitionId="email" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_y8ixssPVEeufrKYRtmlCKQ" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_y8ixs8PVEeufrKYRtmlCKQ" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_y8ixtMPVEeufrKYRtmlCKQ" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_y8ixtcPVEeufrKYRtmlCKQ" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_y8ixtsPVEeufrKYRtmlCKQ" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_y8ixt8PVEeufrKYRtmlCKQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_y8ixuMPVEeufrKYRtmlCKQ" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_y8ixucPVEeufrKYRtmlCKQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_y8ixusPVEeufrKYRtmlCKQ" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_y8ixu8PVEeufrKYRtmlCKQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_y8ixvMPVEeufrKYRtmlCKQ" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_y8ixvcPVEeufrKYRtmlCKQ" name="bpms.loves.beer@gmail.com" content="bpms.loves.beer@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_y8ixvsPVEeufrKYRtmlCKQ" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_y8ixv8PVEeufrKYRtmlCKQ" name="hnjiybihahojemfo" content="hnjiybihahojemfo" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_y8ixwMPVEeufrKYRtmlCKQ" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_y8ixwcPVEeufrKYRtmlCKQ" name="bpms.loves.beer@gmail.com" content="bpms.loves.beer@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_y8ixwsPVEeufrKYRtmlCKQ" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_y8ixw8PVEeufrKYRtmlCKQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_y8ixxMPVEeufrKYRtmlCKQ" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_y8ixxcPVEeufrKYRtmlCKQ" name="david.crittin@students.hevs.ch" content="david.crittin@students.hevs.ch" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_y8ixxsPVEeufrKYRtmlCKQ" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_y8ixx8PVEeufrKYRtmlCKQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_y8ixyMPVEeufrKYRtmlCKQ" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_y8ixycPVEeufrKYRtmlCKQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_y8ixysPVEeufrKYRtmlCKQ" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_y8ixy8PVEeufrKYRtmlCKQ" name="🍻 Les bières sont prêtes 🍻" content="🍻 Les bières sont prêtes 🍻" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_y8ixzMPVEeufrKYRtmlCKQ" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_y8ixzcPVEeufrKYRtmlCKQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_y8ixzsPVEeufrKYRtmlCKQ" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_y8ixz8PVEeufrKYRtmlCKQ" name="&lt;pattern-expression>" content="&lt;p>🍻 Il est l&amp;#39;heure de venir d&amp;eacute;guster ! 🍻&lt;/p>&#xA;" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_y8ix0MPVEeufrKYRtmlCKQ" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_y8ix0cPVEeufrKYRtmlCKQ"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_y8ix0sPVEeufrKYRtmlCKQ" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_y8ix08PVEeufrKYRtmlCKQ" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_y8ix1MPVEeufrKYRtmlCKQ" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_y8ix1cPVEeufrKYRtmlCKQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_y8ix1sPVEeufrKYRtmlCKQ" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_y8ix18PVEeufrKYRtmlCKQ"/>
              </parameters>
            </configuration>
          </connectors>
          <connectors xmi:type="process:Connector" xmi:id="_mKozMMPaEeufrKYRtmlCKQ" name="CreateFile" definitionId="scripting-shell" event="ON_FINISH" ignoreErrors="true" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_mKozMcPaEeufrKYRtmlCKQ" definitionId="scripting-shell" version="1.0.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mKozMsPaEeufrKYRtmlCKQ" key="interpreter">
                <expression xmi:type="expression:Expression" xmi:id="_mKozM8PaEeufrKYRtmlCKQ" name="cmd" content="cmd" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mKozNMPaEeufrKYRtmlCKQ" key="parameter">
                <expression xmi:type="expression:Expression" xmi:id="_mKozNcPaEeufrKYRtmlCKQ" name="/c" content="/c" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mKozNsPaEeufrKYRtmlCKQ" key="script">
                <expression xmi:type="expression:Expression" xmi:id="_mKozN8PaEeufrKYRtmlCKQ" name="&lt;pattern-expression>" content="echo &quot;Biere préparée&quot; > fromBonita.txt" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_mKozOMPaEeufrKYRtmlCKQ">
              <leftOperand xmi:type="expression:Expression" xmi:id="_mKozOcPaEeufrKYRtmlCKQ"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_mKozOsPaEeufrKYRtmlCKQ" name="result" content="result" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Object">
                <referencedElements xmi:type="definition:Output" xmi:id="_mKozO8PaEeufrKYRtmlCKQ" name="result" type="java.lang.Object"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_mKozPMPaEeufrKYRtmlCKQ" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_mKozPcPaEeufrKYRtmlCKQ">
              <leftOperand xmi:type="expression:Expression" xmi:id="_mKozPsPaEeufrKYRtmlCKQ"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_mKozP8PaEeufrKYRtmlCKQ" name="exitStatus" content="exitStatus" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Object">
                <referencedElements xmi:type="definition:Output" xmi:id="_mKozQMPaEeufrKYRtmlCKQ" name="exitStatus" type="java.lang.Object"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_mKozQcPaEeufrKYRtmlCKQ" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_F_HfhLi5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_F_Hfhbi5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_F_Hfhri5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_F_HfiLi5EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_F_Hfh7i5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_6ZXLGri9EeuOct60VCUhnQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_fV_3oMPPEeufrKYRtmlCKQ" name="stockageBouteillesForm" content="580f95b1-cd3b-428f-b81d-d7ed10dcacee" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_6ZXLGbi9EeuOct60VCUhnQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_6ZXLHLi9EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_fOD-QMO8Eeu5jNNAa7IUcQ" name="Matériel stérilisé ?" outgoing="__BIkQLi5EeuOct60VCUhnQ _NOokwLi6EeuOct60VCUhnQ" incoming="_r3oj0Li5EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_r3goAri5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_r3goAbi5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_r3goA7i5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_ZLc-wMPAEeum97Fokdr50Q" name="Porte2" outgoing="_XKna0Li8EeuOct60VCUhnQ _k4Q2kLi8EeuOct60VCUhnQ" incoming="_V4u8MLi8EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_V4rR0ri8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_V4rR0bi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_V4rR07i8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_ZkbNgMPCEeufrKYRtmlCKQ" name="Gateway1" outgoing="_apR8wMPCEeufrKYRtmlCKQ" incoming="_YTslcMPCEeufrKYRtmlCKQ _aRrVEMPCEeufrKYRtmlCKQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_YTYcYcPCEeufrKYRtmlCKQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_YTYcYMPCEeufrKYRtmlCKQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_YTYcYsPCEeufrKYRtmlCKQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_hCYz4MPCEeufrKYRtmlCKQ" name="Gateway2" outgoing="_esKjYMPCEeufrKYRtmlCKQ" incoming="_ccGlQMPCEeufrKYRtmlCKQ _7sHeULi7EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ccAeocPCEeufrKYRtmlCKQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ccAeoMPCEeufrKYRtmlCKQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ccAeosPCEeufrKYRtmlCKQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_xdrVEMPXEeufrKYRtmlCKQ" name="Ajout du malt dans la cuve " outgoing="_scSTkLi6EeuOct60VCUhnQ" incoming="_Lrn54Li6EeuOct60VCUhnQ _NOokwLi6EeuOct60VCUhnQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bEYegri4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bEYegbi4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bEYeg7i4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_bEYehLi4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_bEYehbi4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_bEYehri4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_bEZFkLi4EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_bEYeh7i4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_xdtKQsPXEeufrKYRtmlCKQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_xdtKQ8PXEeufrKYRtmlCKQ" name="ajoutMaltCuveForm" content="2b65d624-bf54-4dc2-b8ce-f5d94db4e4a7" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_xdtKQcPXEeufrKYRtmlCKQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_xdtKRMPXEeufrKYRtmlCKQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_1jmooMPXEeufrKYRtmlCKQ" name="Annoncer un retard" outgoing="_2C7o8MPXEeufrKYRtmlCKQ" incoming="_1jtWUMPXEeufrKYRtmlCKQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1jnPscPXEeufrKYRtmlCKQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1jnPsMPXEeufrKYRtmlCKQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1jnPssPXEeufrKYRtmlCKQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_1jnPs8PXEeufrKYRtmlCKQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_1jnPtMPXEeufrKYRtmlCKQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_1jnPtcPXEeufrKYRtmlCKQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_1jnPt8PXEeufrKYRtmlCKQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_1jnPtsPXEeufrKYRtmlCKQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_Tkw5sMPZEeufrKYRtmlCKQ" name="Premier palier de brassage - 15mn@45°" outgoing="_il3hYMPZEeufrKYRtmlCKQ" incoming="_UJqWgMPZEeufrKYRtmlCKQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_mPP4UcPYEeufrKYRtmlCKQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_mPP4UMPYEeufrKYRtmlCKQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_mPP4UsPYEeufrKYRtmlCKQ" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_-YZpoMPYEeufrKYRtmlCKQ" name="00:00:05" content="5000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_WGhEwMPZEeufrKYRtmlCKQ" name="Second palier de brassage - 30mn@60°" outgoing="_jeYdwMPZEeufrKYRtmlCKQ" incoming="_il3hYMPZEeufrKYRtmlCKQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_WGhEwcPZEeufrKYRtmlCKQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_WGhEwsPZEeufrKYRtmlCKQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_WGhEw8PZEeufrKYRtmlCKQ" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_WGhExMPZEeufrKYRtmlCKQ" name="00:00:05" content="5000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_aJ3lcMPZEeufrKYRtmlCKQ" name="Troisième palier de brassage - 30mn@70°" outgoing="_kXWtIMPZEeufrKYRtmlCKQ" incoming="_jeYdwMPZEeufrKYRtmlCKQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_aJ3lccPZEeufrKYRtmlCKQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_aJ3lcsPZEeufrKYRtmlCKQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_aJ3lc8PZEeufrKYRtmlCKQ" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_aJ3ldMPZEeufrKYRtmlCKQ" name="00:00:05" content="5000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_dn-rEMPZEeufrKYRtmlCKQ" name="Quatrième palier de brassage - 10mn@78°" outgoing="_lH3kEMPZEeufrKYRtmlCKQ" incoming="_kXWtIMPZEeufrKYRtmlCKQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dn-rEcPZEeufrKYRtmlCKQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dn-rEsPZEeufrKYRtmlCKQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dn-rE8PZEeufrKYRtmlCKQ" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_dn-rFMPZEeufrKYRtmlCKQ" name="00:00:05" content="5000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_BOTnEMSaEeuO8sueqVfXJA" name="Choix du nom de la bière" outgoing="_rIzuYMR_EeuDrfIRDXGjmg" incoming="_q6qksMR_EeuDrfIRDXGjmg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_q6SxQcR_EeuDrfIRDXGjmg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_q6SxQMR_EeuDrfIRDXGjmg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_q6SxQsR_EeuDrfIRDXGjmg" name="" content="" returnTypeFixed="true"/>
          <data xmi:type="process:Data" xmi:id="_pArmcMSOEeuDrfIRDXGjmg" name="titre" dataType="_TjN0sa8zEeuSJd-ffsoCUg">
            <defaultValue xmi:type="expression:Expression" xmi:id="_pArmccSOEeuDrfIRDXGjmg" content=""/>
          </data>
          <data xmi:type="process:Data" xmi:id="_LEtQAMSQEeuDrfIRDXGjmg" name="select" dataType="_TjN0sa8zEeuSJd-ffsoCUg">
            <defaultValue xmi:type="expression:Expression" xmi:id="_LEtQAcSQEeuDrfIRDXGjmg" content=""/>
          </data>
          <data xmi:type="process:JavaObjectData" xmi:id="_teCQoMSQEeuDrfIRDXGjmg" name="select_list" dataType="_TjN0sq8zEeuSJd-ffsoCUg" className="java.util.List">
            <defaultValue xmi:type="expression:Expression" xmi:id="_teCQocSQEeuDrfIRDXGjmg" content="" returnType="java.util.List"/>
          </data>
          <data xmi:type="process:JavaObjectData" xmi:id="_SvaKgMSTEeuDrfIRDXGjmg" name="select_arraylist" dataType="_TjN0sq8zEeuSJd-ffsoCUg" className="java.util.ArrayList">
            <defaultValue xmi:type="expression:Expression" xmi:id="_SvaKgcSTEeuDrfIRDXGjmg" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.ArrayList"/>
          </data>
          <connectors xmi:type="process:Connector" xmi:id="_RJtLQMSDEeuDrfIRDXGjmg" name="sauvegardeNomBiere" definitionId="database-mysql" event="ON_FINISH" ignoreErrors="true" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_RJtLQcSDEeuDrfIRDXGjmg" definitionId="database-mysql" version="1.0.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_RJtLQsSDEeuDrfIRDXGjmg" key="driver">
                <expression xmi:type="expression:Expression" xmi:id="_RJtLQ8SDEeuDrfIRDXGjmg" name="com.mysql.jdbc.Driver" content="com.mysql.jdbc.Driver" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_RJtLRMSDEeuDrfIRDXGjmg" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_RJtLRcSDEeuDrfIRDXGjmg" name="jdbc:mysql://db4free.net:3306/bpms_biere?characterEncoding=latin1&amp;useConfigs=maxPerformance" content="jdbc:mysql://db4free.net:3306/bpms_biere?characterEncoding=latin1&amp;useConfigs=maxPerformance" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_RJtLRsSDEeuDrfIRDXGjmg" key="script">
                <expression xmi:type="expression:Expression" xmi:id="_RJtLR8SDEeuDrfIRDXGjmg" name="&lt;pattern-expression>" content="INSERT INTO `bieres` (`id`, `nom`) VALUES (NULL, '${brasserie.nomBiere}');" type="TYPE_PATTERN" returnTypeFixed="true">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_9sOqoMSdEeuRM5zPXsTHUA" name="brasserie.nomBiere" content="brasserie.nomBiere" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                    <referencedElements xmi:type="expression:Expression" xmi:id="_9sOqocSdEeuRM5zPXsTHUA" name="brasserie" content="brasserie" type="TYPE_VARIABLE" returnType="com.company.model.Brasserie">
                      <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_9sOqosSdEeuRM5zPXsTHUA" name="brasserie" dataType="_TjN0tK8zEeuSJd-ffsoCUg" className="com.company.model.Brasserie"/>
                    </referencedElements>
                  </referencedElements>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_RJtLSMSDEeuDrfIRDXGjmg" key="username">
                <expression xmi:type="expression:Expression" xmi:id="_RJtLScSDEeuDrfIRDXGjmg" name="bpms_biere" content="bpms_biere" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_RJtLSsSDEeuDrfIRDXGjmg" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_RJtLS8SDEeuDrfIRDXGjmg" name="bierebiere" content="bierebiere" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_RJtLTMSDEeuDrfIRDXGjmg" key="separator">
                <expression xmi:type="expression:Expression" xmi:id="_RJtLTcSDEeuDrfIRDXGjmg" name=";" content=";" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_RJtLTsSDEeuDrfIRDXGjmg" key="outputType">
                <expression xmi:type="expression:Expression" xmi:id="_RJtLT8SDEeuDrfIRDXGjmg" name="outputType" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_RJtLUMSDEeuDrfIRDXGjmg" key="wizardMode">
                <expression xmi:type="expression:Expression" xmi:id="_RJtLUcSDEeuDrfIRDXGjmg" name="true" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
            </configuration>
          </connectors>
          <operations xmi:type="expression:Operation" xmi:id="_EWxM0cSaEeuO8sueqVfXJA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_EWxM0sSaEeuO8sueqVfXJA" name="brasserie" content="brasserie" type="TYPE_VARIABLE" returnType="com.company.model.Brasserie">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_EWxM08SaEeuO8sueqVfXJA" name="brasserie" dataType="_TjN0tK8zEeuSJd-ffsoCUg" className="com.company.model.Brasserie"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_EWxM1MSaEeuO8sueqVfXJA" name="brasserieInput.nomBiere" content="brasserieInput?.nomBiere" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_EWxM1cSaEeuO8sueqVfXJA" name="brasserieInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_EWxM1sSaEeuO8sueqVfXJA" type="JAVA_METHOD" expression="setNomBiere">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_q6SxQ8R_EeuDrfIRDXGjmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_q6SxRMR_EeuDrfIRDXGjmg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_q6SxRcR_EeuDrfIRDXGjmg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_q6SxR8R_EeuDrfIRDXGjmg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_q6SxRsR_EeuDrfIRDXGjmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_BOmiBcSaEeuO8sueqVfXJA">
            <targetForm xmi:type="expression:Expression" xmi:id="_GdJqgMSaEeuO8sueqVfXJA" name="nomBiereForm2" content="19c02a6a-9e29-47dc-9462-bba09129ecb8" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_BOmiBMSaEeuO8sueqVfXJA">
            <inputs xmi:type="process:ContractInput" xmi:id="_EWvXoMSaEeuO8sueqVfXJA" name="brasserieInput" type="COMPLEX" dataReference="brasserie" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_EWvXocSaEeuO8sueqVfXJA" name="nomBiere" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_EWxM0MSaEeuO8sueqVfXJA" expression="brasserieInput?.nomBiere != null" errorMessage="nomBiere is mandatory for Brasserie" name="mandatory_brasserieInput_nomBiere">
              <inputNames>brasserieInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_BOmiB8SaEeuO8sueqVfXJA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_L6-HgMO9Eeum97Fokdr50Q" name="brasserie" dataType="_TjN0tK8zEeuSJd-ffsoCUg" className="com.company.model.Brasserie">
        <defaultValue xmi:type="expression:Expression" xmi:id="_X9MjQcO9Eeum97Fokdr50Q" name="initBrasserie()" content="def brasserieVar = new com.company.model.Brasserie()&#xD;&#xA;brasserieVar.isMaterielSterilise = brasserieInput?.isMaterielSterilise&#xD;&#xA;return brasserieVar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Brasserie">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_X9MjQsO9Eeum97Fokdr50Q" name="brasserieInput" type="COMPLEX"/>
        </defaultValue>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_TjN0lK8zEeuSJd-ffsoCUg">
        <targetForm xmi:type="expression:Expression" xmi:id="_ZRfSJcO8Eeu5jNNAa7IUcQ" name="brasserieForm" content="f6429d0f-1e1c-4869-846b-374f9eb0d308" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_TjN0lq8zEeuSJd-ffsoCUg">
        <targetForm xmi:type="expression:Expression" xmi:id="_p7mFsMPBEeum97Fokdr50Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4_F-wLi4EeuOct60VCUhnQ" target="_4_C7cLi4EeuOct60VCUhnQ" source="_2S9vsLi4EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4_Gl0Li4EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_4_Gl0bi4EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_9mfnsLi4EeuOct60VCUhnQ" target="_9maIILi4EeuOct60VCUhnQ" source="_4_C7cLi4EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_9mfnsbi4EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_9mfnsri4EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OiufULi5EeuOct60VCUhnQ" target="_OiqN4Li5EeuOct60VCUhnQ" source="_6ZXLELi9EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OiufUbi5EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_OiufUri5EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_r3oj0Li5EeuOct60VCUhnQ" target="_fOD-QMO8Eeu5jNNAa7IUcQ" source="_TjN0h68zEeuSJd-ffsoCUg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_r3pK4Li5EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_r3pK4bi5EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__BIkQLi5EeuOct60VCUhnQ" target="_PsEQgLi6EeuOct60VCUhnQ" source="_fOD-QMO8Eeu5jNNAa7IUcQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__BIkQbi5EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="__BIkQri5EeuOct60VCUhnQ" name="newScript()" content="brasserie.isMaterielSterilise == false&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Ql3wYMO9Eeum97Fokdr50Q" name="brasserie" dataType="_TjN0tK8zEeuSJd-ffsoCUg" className="com.company.model.Brasserie"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Lrn54Li6EeuOct60VCUhnQ" target="_xdrVEMPXEeufrKYRtmlCKQ" source="_PsEQgLi6EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Lrn54bi6EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_Lrn54ri6EeuOct60VCUhnQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NOokwLi6EeuOct60VCUhnQ" target="_xdrVEMPXEeufrKYRtmlCKQ" source="_fOD-QMO8Eeu5jNNAa7IUcQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NOpL0Li6EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_NOpL0bi6EeuOct60VCUhnQ" name="newScript()" content="brasserie.isMaterielSterilise == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_SsSqUMO9Eeum97Fokdr50Q" name="brasserie" dataType="_TjN0tK8zEeuSJd-ffsoCUg" className="com.company.model.Brasserie"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_scSTkLi6EeuOct60VCUhnQ" target="_scOCILi6EeuOct60VCUhnQ" source="_xdrVEMPXEeufrKYRtmlCKQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_scSTkbi6EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_scSTkri6EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3GaT8Li6EeuOct60VCUhnQ" target="_3GXQoLi6EeuOct60VCUhnQ" source="_scOCILi6EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3GaT8bi6EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_3GaT8ri6EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4b45ILi6EeuOct60VCUhnQ" target="_4b110Li6EeuOct60VCUhnQ" source="_3GXQoLi6EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4b45Ibi6EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_4b45Iri6EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_46cdYLi6EeuOct60VCUhnQ" target="_46YL8Li6EeuOct60VCUhnQ" source="_3GXQoLi6EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_46cdYbi6EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_46cdYri6EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_wtf0oLi7EeuOct60VCUhnQ" target="_wtcKQLi7EeuOct60VCUhnQ" source="_brycwLi4EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_wtf0obi7EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_wtf0ori7EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xLBeILi7EeuOct60VCUhnQ" target="_xK-a0Li7EeuOct60VCUhnQ" source="_wtcKQLi7EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xLBeIbi7EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_xLBeIri7EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xwAagLi7EeuOct60VCUhnQ" target="_xv9XMLi7EeuOct60VCUhnQ" source="_wtcKQLi7EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xwBBkLi7EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_xwBBkbi7EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7sHeULi7EeuOct60VCUhnQ" target="_hCYz4MPCEeufrKYRtmlCKQ" source="_xK-a0Li7EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7sHeUbi7EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_7sHeUri7EeuOct60VCUhnQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_FwOAgLi8EeuOct60VCUhnQ" target="_FwJvELi8EeuOct60VCUhnQ" source="_9maIILi4EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_FwOAgbi8EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_FwOAgri8EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JtCbYLi8EeuOct60VCUhnQ" target="_Js-J8Li8EeuOct60VCUhnQ" source="_FwJvELi8EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JtCbYbi8EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_JtCbYri8EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SNFJ0Li8EeuOct60VCUhnQ" target="_SNBfcLi8EeuOct60VCUhnQ" source="_Js-J8Li8EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SNFJ0bi8EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_SNFJ0ri8EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_V4u8MLi8EeuOct60VCUhnQ" target="_ZLc-wMPAEeum97Fokdr50Q" source="_SNBfcLi8EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_V4u8Mbi8EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_V4u8Mri8EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XKna0Li8EeuOct60VCUhnQ" target="_40qTkLi8EeuOct60VCUhnQ" source="_ZLc-wMPAEeum97Fokdr50Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XKna0bi8EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_XKna0ri8EeuOct60VCUhnQ" name="newScript()" content="brasserie.densiteBiere &lt; 25" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_ctKyAMPAEeum97Fokdr50Q" name="brasserie" dataType="_TjN0tK8zEeuSJd-ffsoCUg" className="com.company.model.Brasserie"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_fHACkLi8EeuOct60VCUhnQ" target="_fG1qgLi8EeuOct60VCUhnQ" source="_40qTkLi8EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_fHACkbi8EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_fHACkri8EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_k4Q2kLi8EeuOct60VCUhnQ" target="_EgIZALi5EeuOct60VCUhnQ" source="_ZLc-wMPAEeum97Fokdr50Q" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_k4Q2kbi8EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_k4RdoLi8EeuOct60VCUhnQ" name="densiteBiere >= 25" content="brasserie.densiteBiere >= 25" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_f7u_wMPAEeum97Fokdr50Q" name="brasserie" dataType="_TjN0tK8zEeuSJd-ffsoCUg" className="com.company.model.Brasserie"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_pp8c4Li8EeuOct60VCUhnQ" target="_pp5ZkLi8EeuOct60VCUhnQ" source="_EgIZALi5EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_pp8c4bi8EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_pp8c4ri8EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_p697cLi8EeuOct60VCUhnQ" target="_p66RELi8EeuOct60VCUhnQ" source="_pp5ZkLi8EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_p697cbi8EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_p6-igLi8EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vO4sILi8EeuOct60VCUhnQ" target="_6ZXLELi9EeuOct60VCUhnQ" source="_p66RELi8EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vO4sIbi8EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_vO4sIri8EeuOct60VCUhnQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_YTslcMPCEeufrKYRtmlCKQ" target="_ZkbNgMPCEeufrKYRtmlCKQ" source="_46YL8Li6EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_YTslccPCEeufrKYRtmlCKQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_YTslcsPCEeufrKYRtmlCKQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_aRrVEMPCEeufrKYRtmlCKQ" target="_ZkbNgMPCEeufrKYRtmlCKQ" source="_4b110Li6EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_aRr8IMPCEeufrKYRtmlCKQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_aRr8IcPCEeufrKYRtmlCKQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_apR8wMPCEeufrKYRtmlCKQ" target="_GEzl4Li7EeuOct60VCUhnQ" source="_ZkbNgMPCEeufrKYRtmlCKQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_apR8wcPCEeufrKYRtmlCKQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_apR8wsPCEeufrKYRtmlCKQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ccGlQMPCEeufrKYRtmlCKQ" target="_hCYz4MPCEeufrKYRtmlCKQ" source="_xv9XMLi7EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ccGlQcPCEeufrKYRtmlCKQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_ccHMUMPCEeufrKYRtmlCKQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_esKjYMPCEeufrKYRtmlCKQ" target="_2S9vsLi4EeuOct60VCUhnQ" source="_hCYz4MPCEeufrKYRtmlCKQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_esKjYcPCEeufrKYRtmlCKQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_esKjYsPCEeufrKYRtmlCKQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1jtWUMPXEeufrKYRtmlCKQ" target="_1jmooMPXEeufrKYRtmlCKQ" source="_zA3mIMPXEeufrKYRtmlCKQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1jtWUcPXEeufrKYRtmlCKQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_1jtWUsPXEeufrKYRtmlCKQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2C7o8MPXEeufrKYRtmlCKQ" target="_TjN0h68zEeuSJd-ffsoCUg" source="_1jmooMPXEeufrKYRtmlCKQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2C7o8cPXEeufrKYRtmlCKQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_2C7o8sPXEeufrKYRtmlCKQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_UJqWgMPZEeufrKYRtmlCKQ" target="_Tkw5sMPZEeufrKYRtmlCKQ" source="_GEzl4Li7EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_UJq9kMPZEeufrKYRtmlCKQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_UJq9kcPZEeufrKYRtmlCKQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_il3hYMPZEeufrKYRtmlCKQ" target="_WGhEwMPZEeufrKYRtmlCKQ" source="_Tkw5sMPZEeufrKYRtmlCKQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_il3hYcPZEeufrKYRtmlCKQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_il3hYsPZEeufrKYRtmlCKQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jeYdwMPZEeufrKYRtmlCKQ" target="_aJ3lcMPZEeufrKYRtmlCKQ" source="_WGhEwMPZEeufrKYRtmlCKQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jeYdwcPZEeufrKYRtmlCKQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_jeYdwsPZEeufrKYRtmlCKQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kXWtIMPZEeufrKYRtmlCKQ" target="_dn-rEMPZEeufrKYRtmlCKQ" source="_aJ3lcMPZEeufrKYRtmlCKQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kXXUMMPZEeufrKYRtmlCKQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_kXXUMcPZEeufrKYRtmlCKQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lH3kEMPZEeufrKYRtmlCKQ" target="_brycwLi4EeuOct60VCUhnQ" source="_dn-rEMPZEeufrKYRtmlCKQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lH3kEcPZEeufrKYRtmlCKQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_lH3kEsPZEeufrKYRtmlCKQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_q6qksMR_EeuDrfIRDXGjmg" target="_BOTnEMSaEeuO8sueqVfXJA" source="_TjN0g68zEeuSJd-ffsoCUg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_q6rLwMR_EeuDrfIRDXGjmg"/>
        <condition xmi:type="expression:Expression" xmi:id="_q6rLwcR_EeuDrfIRDXGjmg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rIzuYMR_EeuDrfIRDXGjmg" target="_TjN0h68zEeuSJd-ffsoCUg" source="_BOTnEMSaEeuO8sueqVfXJA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rIzuYcR_EeuDrfIRDXGjmg"/>
        <condition xmi:type="expression:Expression" xmi:id="_rIzuYsR_EeuDrfIRDXGjmg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_TjN0m68zEeuSJd-ffsoCUg" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_TjN0nK8zEeuSJd-ffsoCUg">
        <inputs xmi:type="process:ContractInput" xmi:id="_X9L8MMO9Eeum97Fokdr50Q" name="brasserieInput" type="COMPLEX" dataReference="brasserie">
          <inputs xmi:type="process:ContractInput" xmi:id="_X9L8McO9Eeum97Fokdr50Q" name="isMaterielSterilise" type="BOOLEAN"/>
        </inputs>
        <constraints xmi:type="process:ContractConstraint" xmi:id="_X9MjQMO9Eeum97Fokdr50Q" expression="brasserieInput?.isMaterielSterilise != null" errorMessage="isMaterielSterilise is mandatory for Brasserie" name="mandatory_brasserieInput_isMaterielSterilise">
          <inputNames>brasserieInput</inputNames>
        </constraints>
      </contract>
      <documents xmi:type="process:Document" xmi:id="_3tXsEMSIEeuDrfIRDXGjmg" name="test">
        <mimeType xmi:type="expression:Expression" xmi:id="_3tXsEcSIEeuDrfIRDXGjmg" name="" content="" returnTypeFixed="true"/>
        <url xmi:type="expression:Expression" xmi:id="_3tXsEsSIEeuDrfIRDXGjmg" name="" content="" returnTypeFixed="true"/>
        <initialMultipleContent xmi:type="expression:Expression" xmi:id="_3tXsE8SIEeuDrfIRDXGjmg" name="" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List" returnTypeFixed="true"/>
      </documents>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TjN0na8zEeuSJd-ffsoCUg">
        <name xmi:type="expression:Expression" xmi:id="_TjN0nq8zEeuSJd-ffsoCUg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TjN0n68zEeuSJd-ffsoCUg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TjN0oK8zEeuSJd-ffsoCUg">
        <name xmi:type="expression:Expression" xmi:id="_TjN0oa8zEeuSJd-ffsoCUg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TjN0oq8zEeuSJd-ffsoCUg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TjN0o68zEeuSJd-ffsoCUg">
        <name xmi:type="expression:Expression" xmi:id="_TjN0pK8zEeuSJd-ffsoCUg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TjN0pa8zEeuSJd-ffsoCUg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TjN0pq8zEeuSJd-ffsoCUg">
        <name xmi:type="expression:Expression" xmi:id="_TjN0p68zEeuSJd-ffsoCUg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TjN0qK8zEeuSJd-ffsoCUg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TjN0qa8zEeuSJd-ffsoCUg">
        <name xmi:type="expression:Expression" xmi:id="_TjN0qq8zEeuSJd-ffsoCUg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TjN0q68zEeuSJd-ffsoCUg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_TjN0rK8zEeuSJd-ffsoCUg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_TjN0ra8zEeuSJd-ffsoCUg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_TjN0rq8zEeuSJd-ffsoCUg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_TjN0r68zEeuSJd-ffsoCUg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_TjN0sK8zEeuSJd-ffsoCUg" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_TjN0sa8zEeuSJd-ffsoCUg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_TjN0sq8zEeuSJd-ffsoCUg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_TjN0s68zEeuSJd-ffsoCUg" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_TjN0tK8zEeuSJd-ffsoCUg" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_TjN0ta8zEeuSJd-ffsoCUg" type="Process" element="_TjN0gK8zEeuSJd-ffsoCUg" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_TjN0tq8zEeuSJd-ffsoCUg" type="2007" element="_TjN0ga8zEeuSJd-ffsoCUg">
      <children xmi:type="notation:DecorationNode" xmi:id="_TjN0t68zEeuSJd-ffsoCUg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_TjN0uK8zEeuSJd-ffsoCUg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_TjN0ua8zEeuSJd-ffsoCUg" type="3007" element="_TjN0gq8zEeuSJd-ffsoCUg">
          <children xmi:type="notation:DecorationNode" xmi:id="_TjN0uq8zEeuSJd-ffsoCUg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_TjN0u68zEeuSJd-ffsoCUg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_TjN0vK8zEeuSJd-ffsoCUg" type="3005" element="_TjN0h68zEeuSJd-ffsoCUg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_TjN0va8zEeuSJd-ffsoCUg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TjN0vq8zEeuSJd-ffsoCUg" x="251" y="58" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_TjN0v68zEeuSJd-ffsoCUg" type="3002" element="_TjN0g68zEeuSJd-ffsoCUg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_TjN0wK8zEeuSJd-ffsoCUg" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_TjN0wa8zEeuSJd-ffsoCUg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TjN0wq8zEeuSJd-ffsoCUg" x="42" y="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_brycybi4EeuOct60VCUhnQ" type="3027" element="_brycwLi4EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_brycy7i4EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_brycyri4EeuOct60VCUhnQ" x="2265" y="59" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2S-90Li4EeuOct60VCUhnQ" type="3027" element="_2S9vsLi4EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_2S-90ri4EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2S-90bi4EeuOct60VCUhnQ" x="2777" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4_Dihbi4EeuOct60VCUhnQ" type="3027" element="_4_C7cLi4EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4_EJkLi4EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4_Dihri4EeuOct60VCUhnQ" x="2892" y="62" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_9mb9ULi4EeuOct60VCUhnQ" type="3027" element="_9maIILi4EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_9mb9Uri4EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9mb9Ubi4EeuOct60VCUhnQ" x="3063" y="58" width="136" height="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_EgJnILi5EeuOct60VCUhnQ" type="3027" element="_EgIZALi5EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_EgJnIri5EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EgJnIbi5EeuOct60VCUhnQ" x="3952" y="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Oiq08Li5EeuOct60VCUhnQ" type="3003" element="_OiqN4Li5EeuOct60VCUhnQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Oiq08ri5EeuOct60VCUhnQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Oiq087i5EeuOct60VCUhnQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Oiq08bi5EeuOct60VCUhnQ" x="4640" y="86"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PsE3lri6EeuOct60VCUhnQ" type="3005" element="_PsEQgLi6EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PsE3mLi6EeuOct60VCUhnQ" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_zA73kMPXEeufrKYRtmlCKQ" type="3043" element="_zA3mIMPXEeufrKYRtmlCKQ" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_zA9FsMPXEeufrKYRtmlCKQ" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_zA9FscPXEeufrKYRtmlCKQ" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zA73kcPXEeufrKYRtmlCKQ"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PsE3l7i6EeuOct60VCUhnQ" x="466" y="136" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_scOpMLi6EeuOct60VCUhnQ" type="3027" element="_scOCILi6EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_scOpMri6EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_scOpMbi6EeuOct60VCUhnQ" x="802" y="59" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_3GX3sLi6EeuOct60VCUhnQ" type="3009" element="_3GXQoLi6EeuOct60VCUhnQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_3GX3sri6EeuOct60VCUhnQ" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_3GX3s7i6EeuOct60VCUhnQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3GX3sbi6EeuOct60VCUhnQ" x="998" y="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4b2c4Li6EeuOct60VCUhnQ" type="3027" element="_4b110Li6EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4b2c4ri6EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4b2c4bi6EeuOct60VCUhnQ" x="1146" y="112" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_46ZaELi6EeuOct60VCUhnQ" type="3027" element="_46YL8Li6EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_46ZaEri6EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_46ZaEbi6EeuOct60VCUhnQ" x="1106" y="15" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_GE0M97i7EeuOct60VCUhnQ" type="3027" element="_GEzl4Li7EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_GE00ALi7EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GE0M-Li7EeuOct60VCUhnQ" x="1353" y="64"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_wtdYYLi7EeuOct60VCUhnQ" type="3009" element="_wtcKQLi7EeuOct60VCUhnQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_wtdYYri7EeuOct60VCUhnQ" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_wtdYY7i7EeuOct60VCUhnQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wtdYYbi7EeuOct60VCUhnQ" x="2459" y="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xK_B4Li7EeuOct60VCUhnQ" type="3027" element="_xK-a0Li7EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_xK_B4ri7EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xK_B4bi7EeuOct60VCUhnQ" x="2582" y="10" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xv9-QLi7EeuOct60VCUhnQ" type="3027" element="_xv9XMLi7EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_xv9-Qri7EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xv9-Qbi7EeuOct60VCUhnQ" x="2582" y="119" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_FwK9MLi8EeuOct60VCUhnQ" type="3027" element="_FwJvELi8EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_FwK9Mri8EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_FwK9Mbi8EeuOct60VCUhnQ" x="3260" y="62" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Js_YELi8EeuOct60VCUhnQ" type="3027" element="_Js-J8Li8EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Js_YEri8EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Js_YEbi8EeuOct60VCUhnQ" x="3454" y="64" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SNCGgLi8EeuOct60VCUhnQ" type="3027" element="_SNBfcLi8EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SNCGgri8EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SNCGgbi8EeuOct60VCUhnQ" x="3675" y="71" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_fG3fsLi8EeuOct60VCUhnQ" type="3050" element="_fG1qgLi8EeuOct60VCUhnQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_fG4GwLi8EeuOct60VCUhnQ" type="5052">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_fG4Gwbi8EeuOct60VCUhnQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fG3fsbi8EeuOct60VCUhnQ" x="3849" y="322"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_pp6AoLi8EeuOct60VCUhnQ" type="3027" element="_pp5ZkLi8EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pp6Aori8EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pp6Aobi8EeuOct60VCUhnQ" x="4108" y="69" width="122" height="61"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_p67fMLi8EeuOct60VCUhnQ" type="3027" element="_p66RELi8EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_p67fMri8EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_p67fMbi8EeuOct60VCUhnQ" x="4279" y="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_40q6rLi8EeuOct60VCUhnQ" type="3005" element="_40qTkLi8EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_40q6rri8EeuOct60VCUhnQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_40q6rbi8EeuOct60VCUhnQ" x="3821" y="217" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6ZXyILi9EeuOct60VCUhnQ" type="3005" element="_6ZXLELi9EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_6ZXyIri9EeuOct60VCUhnQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6ZXyIbi9EeuOct60VCUhnQ" x="4431" y="64" width="146" height="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_fOGagMO8Eeu5jNNAa7IUcQ" type="3008" element="_fOD-QMO8Eeu5jNNAa7IUcQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_fOGagsO8Eeu5jNNAa7IUcQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_fOGag8O8Eeu5jNNAa7IUcQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fOGagcO8Eeu5jNNAa7IUcQ" x="403" y="61" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZLyV8MPAEeum97Fokdr50Q" type="3008" element="_ZLc-wMPAEeum97Fokdr50Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZLyV8sPAEeum97Fokdr50Q" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ZLy9AMPAEeum97Fokdr50Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZLyV8cPAEeum97Fokdr50Q" x="3849" y="78" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Zkb0k8PCEeufrKYRtmlCKQ" type="3051" element="_ZkbNgMPCEeufrKYRtmlCKQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZkcboMPCEeufrKYRtmlCKQ" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ZkcbocPCEeufrKYRtmlCKQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Zkb0lMPCEeufrKYRtmlCKQ" x="1288" y="66" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_hCZa88PCEeufrKYRtmlCKQ" type="3051" element="_hCYz4MPCEeufrKYRtmlCKQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_hCaCAcPCEeufrKYRtmlCKQ" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_hCaCAsPCEeufrKYRtmlCKQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hCaCAMPCEeufrKYRtmlCKQ" x="2717" y="80" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xduYYMPXEeufrKYRtmlCKQ" type="3005" element="_xdrVEMPXEeufrKYRtmlCKQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_xdu_cMPXEeufrKYRtmlCKQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xduYYcPXEeufrKYRtmlCKQ" x="612" y="61" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1jn2wMPXEeufrKYRtmlCKQ" type="3027" element="_1jmooMPXEeufrKYRtmlCKQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_1jod0MPXEeufrKYRtmlCKQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1jn2wcPXEeufrKYRtmlCKQ" x="441" y="255"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Tkxgw8PZEeufrKYRtmlCKQ" type="3017" element="_Tkw5sMPZEeufrKYRtmlCKQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_TkyH0MPZEeufrKYRtmlCKQ" type="5032">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_TkyH0cPZEeufrKYRtmlCKQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TkxgxMPZEeufrKYRtmlCKQ" x="1562" y="78" width="30" height="30"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_WGhr0MPZEeufrKYRtmlCKQ" type="3017" element="_WGhEwMPZEeufrKYRtmlCKQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_WGhr0cPZEeufrKYRtmlCKQ" type="5032" element="_WGhEwMPZEeufrKYRtmlCKQ">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_WGhr0sPZEeufrKYRtmlCKQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WGhr08PZEeufrKYRtmlCKQ" x="1743" y="118" width="30" height="30"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_aJ4MgMPZEeufrKYRtmlCKQ" type="3017" element="_aJ3lcMPZEeufrKYRtmlCKQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_aJ4MgcPZEeufrKYRtmlCKQ" type="5032" element="_aJ3lcMPZEeufrKYRtmlCKQ">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_aJ4MgsPZEeufrKYRtmlCKQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_aJ4Mg8PZEeufrKYRtmlCKQ" x="1904" y="156" width="30" height="30"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_dn-rFcPZEeufrKYRtmlCKQ" type="3017" element="_dn-rEMPZEeufrKYRtmlCKQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_dn-rFsPZEeufrKYRtmlCKQ" type="5032" element="_dn-rEMPZEeufrKYRtmlCKQ">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_dn-rF8PZEeufrKYRtmlCKQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dn-rGMPZEeufrKYRtmlCKQ" x="2094" y="191" width="30" height="30"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_BO3AsMSaEeuO8sueqVfXJA" type="3005" element="_BOTnEMSaEeuO8sueqVfXJA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_BO3nwMSaEeuO8sueqVfXJA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BO3AscSaEeuO8sueqVfXJA" x="99" y="59" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_TjN0w68zEeuSJd-ffsoCUg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_TjN0xK8zEeuSJd-ffsoCUg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_TjN0xa8zEeuSJd-ffsoCUg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_TjN0xq8zEeuSJd-ffsoCUg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TjN0x68zEeuSJd-ffsoCUg" x="23" y="10" width="4763" height="469"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_TjN0yK8zEeuSJd-ffsoCUg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_TjN0ya8zEeuSJd-ffsoCUg" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_TjN0yq8zEeuSJd-ffsoCUg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_TjN0y68zEeuSJd-ffsoCUg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TjN0zK8zEeuSJd-ffsoCUg" width="4786" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_TjN0za8zEeuSJd-ffsoCUg"/>
    <edges xmi:type="notation:Connector" xmi:id="_4_Gl0ri4EeuOct60VCUhnQ" type="4001" element="_4_F-wLi4EeuOct60VCUhnQ" source="_2S-90Li4EeuOct60VCUhnQ" target="_4_Dihbi4EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4_Gl1bi4EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4_Gl1ri4EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4_Gl07i4EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4_Gl1Li4EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_9mgOwLi4EeuOct60VCUhnQ" type="4001" element="_9mfnsLi4EeuOct60VCUhnQ" source="_4_Dihbi4EeuOct60VCUhnQ" target="_9mb9ULi4EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_9mgOw7i4EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_9mgOxLi4EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_9mgOwbi4EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_9mgOwri4EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OivGYLi5EeuOct60VCUhnQ" type="4001" element="_OiufULi5EeuOct60VCUhnQ" source="_6ZXyILi9EeuOct60VCUhnQ" target="_Oiq08Li5EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OivGY7i5EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OivGZLi5EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OivGYbi5EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OivGYri5EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_r3pK4ri5EeuOct60VCUhnQ" type="4001" element="_r3oj0Li5EeuOct60VCUhnQ" source="_TjN0vK8zEeuSJd-ffsoCUg" target="_fOGagMO8Eeu5jNNAa7IUcQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_r3px8Li5EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_r3px8bi5EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_r3pK47i5EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_r3pK5Li5EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__BLnkLi5EeuOct60VCUhnQ" type="4001" element="__BIkQLi5EeuOct60VCUhnQ" source="_fOGagMO8Eeu5jNNAa7IUcQ" target="_PsE3lri6EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__BLnk7i5EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__BLnlLi5EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__BLnkbi5EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__BLnkri5EeuOct60VCUhnQ" points="[-2, -3, -80, -98]$[76, 95, -2, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="__BM1sLi5EeuOct60VCUhnQ" id="(0.46511627906976744,0.9767441860465116)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="__BM1sbi5EeuOct60VCUhnQ" id="(0.016666666666666666,0.55)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Lrog8Li6EeuOct60VCUhnQ" type="4001" element="_Lrn54Li6EeuOct60VCUhnQ" source="_PsE3lri6EeuOct60VCUhnQ" target="_xduYYMPXEeufrKYRtmlCKQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Lrog87i6EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Lrog9Li6EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Lrog8bi6EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Lrog8ri6EeuOct60VCUhnQ" points="[0, 0, -168, 76]$[54, 0, -114, 76]$[54, -61, -114, 15]$[108, -61, -60, 15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_LrpIALi6EeuOct60VCUhnQ" id="(1.0,0.43333333333333335)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NOsPILi6EeuOct60VCUhnQ" type="4001" element="_NOokwLi6EeuOct60VCUhnQ" source="_fOGagMO8Eeu5jNNAa7IUcQ" target="_xduYYMPXEeufrKYRtmlCKQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NOs2MLi6EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NOs2Mbi6EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NOsPIbi6EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NOsPIri6EeuOct60VCUhnQ" points="[0, -10, -302, -9]$[242, -10, -60, -9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_NOtdQLi6EeuOct60VCUhnQ" id="(1.0,0.7209302325581395)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_scSTk7i6EeuOct60VCUhnQ" type="4001" element="_scSTkLi6EeuOct60VCUhnQ" source="_xduYYMPXEeufrKYRtmlCKQ" target="_scOpMLi6EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_scSTlri6EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_scSTl7i6EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_scSTlLi6EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_scSTlbi6EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3Ga7ALi6EeuOct60VCUhnQ" type="4001" element="_3GaT8Li6EeuOct60VCUhnQ" source="_scOpMLi6EeuOct60VCUhnQ" target="_3GX3sLi6EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3Ga7A7i6EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3Ga7BLi6EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3Ga7Abi6EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3Ga7Ari6EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4b45I7i6EeuOct60VCUhnQ" type="4001" element="_4b45ILi6EeuOct60VCUhnQ" source="_3GX3sLi6EeuOct60VCUhnQ" target="_4b2c4Li6EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4b5gMri6EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4b5gM7i6EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4b5gMLi6EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4b5gMbi6EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_46dEcLi6EeuOct60VCUhnQ" type="4001" element="_46cdYLi6EeuOct60VCUhnQ" source="_3GX3sLi6EeuOct60VCUhnQ" target="_46ZaELi6EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_46dEc7i6EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_46dEdLi6EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_46dEcbi6EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_46dEcri6EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wtgbsLi7EeuOct60VCUhnQ" type="4001" element="_wtf0oLi7EeuOct60VCUhnQ" source="_brycybi4EeuOct60VCUhnQ" target="_wtdYYLi7EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wtgbs7i7EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wtgbtLi7EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wtgbsbi7EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wtgbsri7EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xLCFMLi7EeuOct60VCUhnQ" type="4001" element="_xLBeILi7EeuOct60VCUhnQ" source="_wtdYYLi7EeuOct60VCUhnQ" target="_xK_B4Li7EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xLCFM7i7EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xLCFNLi7EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xLCFMbi7EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xLCFMri7EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xwBBkri7EeuOct60VCUhnQ" type="4001" element="_xwAagLi7EeuOct60VCUhnQ" source="_wtdYYLi7EeuOct60VCUhnQ" target="_xv9-QLi7EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xwBooLi7EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xwBoobi7EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xwBBk7i7EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xwBBlLi7EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7sHeU7i7EeuOct60VCUhnQ" type="4001" element="_7sHeULi7EeuOct60VCUhnQ" source="_xK_B4Li7EeuOct60VCUhnQ" target="_hCZa88PCEeufrKYRtmlCKQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7sIFYLi7EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7sIFYbi7EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7sHeVLi7EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7sHeVbi7EeuOct60VCUhnQ" points="[0, 0, -64, -30]$[45, 19, -19, -11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7sIscLi7EeuOct60VCUhnQ" id="(1.0,0.5833333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_FwOAg7i8EeuOct60VCUhnQ" type="4001" element="_FwOAgLi8EeuOct60VCUhnQ" source="_9mb9ULi4EeuOct60VCUhnQ" target="_FwK9MLi8EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_FwOnkLi8EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_FwOnkbi8EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_FwOAhLi8EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_FwOAhbi8EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JtCbY7i8EeuOct60VCUhnQ" type="4001" element="_JtCbYLi8EeuOct60VCUhnQ" source="_FwK9MLi8EeuOct60VCUhnQ" target="_Js_YELi8EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JtCbZri8EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JtCbZ7i8EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JtCbZLi8EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JtCbZbi8EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SNFJ07i8EeuOct60VCUhnQ" type="4001" element="_SNFJ0Li8EeuOct60VCUhnQ" source="_Js_YELi8EeuOct60VCUhnQ" target="_SNCGgLi8EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_SNFJ1ri8EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SNFJ17i8EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SNFJ1Li8EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SNFJ1bi8EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_V4vjQLi8EeuOct60VCUhnQ" type="4001" element="_V4u8MLi8EeuOct60VCUhnQ" source="_SNCGgLi8EeuOct60VCUhnQ" target="_ZLyV8MPAEeum97Fokdr50Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_V4vjQ7i8EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_V4vjRLi8EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_V4vjQbi8EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_V4vjQri8EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XKoB4Li8EeuOct60VCUhnQ" type="4001" element="_XKna0Li8EeuOct60VCUhnQ" source="_ZLyV8MPAEeum97Fokdr50Q" target="_40q6rLi8EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XKoB47i8EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XKoB5Li8EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XKoB4bi8EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XKoB4ri8EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_fHApoLi8EeuOct60VCUhnQ" type="4001" element="_fHACkLi8EeuOct60VCUhnQ" source="_40q6rLi8EeuOct60VCUhnQ" target="_fG3fsLi8EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_fHApo7i8EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_fHAppLi8EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_fHApobi8EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_fHApori8EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_k4VvELi8EeuOct60VCUhnQ" type="4001" element="_k4Q2kLi8EeuOct60VCUhnQ" source="_ZLyV8MPAEeum97Fokdr50Q" target="_EgJnILi5EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_k4VvE7i8EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_k4VvFLi8EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_k4VvEbi8EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_k4VvEri8EeuOct60VCUhnQ" points="[-2, -8, -118, 0]$[94, -3, -22, 5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_k4XkQLi8EeuOct60VCUhnQ" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_k4XkQbi8EeuOct60VCUhnQ" id="(0.22,0.64)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_pp8c47i8EeuOct60VCUhnQ" type="4001" element="_pp8c4Li8EeuOct60VCUhnQ" source="_EgJnILi5EeuOct60VCUhnQ" target="_pp6AoLi8EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pp8c5ri8EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pp8c57i8EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pp8c5Li8EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_pp8c5bi8EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_p6-igbi8EeuOct60VCUhnQ" type="4001" element="_p697cLi8EeuOct60VCUhnQ" source="_pp6AoLi8EeuOct60VCUhnQ" target="_p67fMLi8EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_p6-ihLi8EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_p6-ihbi8EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_p6-igri8EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_p6-ig7i8EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vO4sI7i8EeuOct60VCUhnQ" type="4001" element="_vO4sILi8EeuOct60VCUhnQ" source="_p67fMLi8EeuOct60VCUhnQ" target="_6ZXyILi9EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vO5TMLi8EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vO5TMbi8EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vO4sJLi8EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vO4sJbi8EeuOct60VCUhnQ" points="[0, 4, -73, 0]$[52, 6, -21, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vO56QLi8EeuOct60VCUhnQ" id="(1.0,0.54)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vO56Qbi8EeuOct60VCUhnQ" id="(0.175,0.5666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_YTtzkMPCEeufrKYRtmlCKQ" type="4001" element="_YTslcMPCEeufrKYRtmlCKQ" source="_46ZaELi6EeuOct60VCUhnQ" target="_Zkb0k8PCEeufrKYRtmlCKQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_YTuaoMPCEeufrKYRtmlCKQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_YTuaocPCEeufrKYRtmlCKQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_YTtzkcPCEeufrKYRtmlCKQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_YTtzksPCEeufrKYRtmlCKQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_aRsjMMPCEeufrKYRtmlCKQ" type="4001" element="_aRrVEMPCEeufrKYRtmlCKQ" source="_4b2c4Li6EeuOct60VCUhnQ" target="_Zkb0k8PCEeufrKYRtmlCKQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_aRsjM8PCEeufrKYRtmlCKQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_aRsjNMPCEeufrKYRtmlCKQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_aRsjMcPCEeufrKYRtmlCKQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_aRsjMsPCEeufrKYRtmlCKQ" points="[0, 0, -43, 58]$[41, -39, -2, 19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_aRu_cMPCEeufrKYRtmlCKQ" id="(1.0,0.55)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_apSj0MPCEeufrKYRtmlCKQ" type="4001" element="_apR8wMPCEeufrKYRtmlCKQ" source="_Zkb0k8PCEeufrKYRtmlCKQ" target="_GE0M97i7EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_apTK4MPCEeufrKYRtmlCKQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_apTK4cPCEeufrKYRtmlCKQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_apSj0cPCEeufrKYRtmlCKQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_apSj0sPCEeufrKYRtmlCKQ" points="[-7, -4, -79, 5]$[71, 16, -1, 25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_apVAEMPCEeufrKYRtmlCKQ" id="(1.0,0.7441860465116279)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ccHMUcPCEeufrKYRtmlCKQ" type="4001" element="_ccGlQMPCEeufrKYRtmlCKQ" source="_xv9-QLi7EeuOct60VCUhnQ" target="_hCZa88PCEeufrKYRtmlCKQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ccHzYMPCEeufrKYRtmlCKQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ccHzYcPCEeufrKYRtmlCKQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ccHMUsPCEeufrKYRtmlCKQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ccHMU8PCEeufrKYRtmlCKQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_esLKcMPCEeufrKYRtmlCKQ" type="4001" element="_esKjYMPCEeufrKYRtmlCKQ" source="_hCZa88PCEeufrKYRtmlCKQ" target="_2S-90Li4EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_esLxgMPCEeufrKYRtmlCKQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_esLxgcPCEeufrKYRtmlCKQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_esLKccPCEeufrKYRtmlCKQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_esLKcsPCEeufrKYRtmlCKQ" points="[-11, 1, -78, 18]$[76, 8, 9, 25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_esNmsMPCEeufrKYRtmlCKQ" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1jt9YMPXEeufrKYRtmlCKQ" type="4001" element="_1jtWUMPXEeufrKYRtmlCKQ" source="_zA73kMPXEeufrKYRtmlCKQ" target="_1jn2wMPXEeufrKYRtmlCKQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1jt9Y8PXEeufrKYRtmlCKQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1jt9ZMPXEeufrKYRtmlCKQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1jt9YcPXEeufrKYRtmlCKQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1jt9YsPXEeufrKYRtmlCKQ" points="[0, 13, 162, -75]$[0, 87, 162, -1]$[-112, 87, 50, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2C8QAMPXEeufrKYRtmlCKQ" type="4001" element="_2C7o8MPXEeufrKYRtmlCKQ" source="_1jn2wMPXEeufrKYRtmlCKQ" target="_TjN0vK8zEeuSJd-ffsoCUg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2C8QA8PXEeufrKYRtmlCKQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2C8QBMPXEeufrKYRtmlCKQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2C8QAcPXEeufrKYRtmlCKQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2C8QAsPXEeufrKYRtmlCKQ" points="[-100, -5, 64, 209]$[-142, -5, 22, 209]$[-142, -184, 22, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2C-sQMPXEeufrKYRtmlCKQ" id="(1.0,0.58)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_UJq9ksPZEeufrKYRtmlCKQ" type="4001" element="_UJqWgMPZEeufrKYRtmlCKQ" source="_GE0M97i7EeuOct60VCUhnQ" target="_Tkxgw8PZEeufrKYRtmlCKQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_UJrkoMPZEeufrKYRtmlCKQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_UJrkocPZEeufrKYRtmlCKQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_UJq9k8PZEeufrKYRtmlCKQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_UJq9lMPZEeufrKYRtmlCKQ" points="[0, 0, -124, -97]$[121, 82, -3, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_UJsywMPZEeufrKYRtmlCKQ" id="(1.0,0.64)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_il4IcMPZEeufrKYRtmlCKQ" type="4001" element="_il3hYMPZEeufrKYRtmlCKQ" source="_Tkxgw8PZEeufrKYRtmlCKQ" target="_WGhr0MPZEeufrKYRtmlCKQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_il4vgMPZEeufrKYRtmlCKQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_il4vgcPZEeufrKYRtmlCKQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_il4IccPZEeufrKYRtmlCKQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_il4IcsPZEeufrKYRtmlCKQ" points="[0, -14, -157, -33]$[166, -14, 9, -33]$[166, 11, 9, -8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_il59oMPZEeufrKYRtmlCKQ" id="(1.0,0.9666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_il6ksMPZEeufrKYRtmlCKQ" id="(0.2,0.26666666666666666)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jeZE0MPZEeufrKYRtmlCKQ" type="4001" element="_jeYdwMPZEeufrKYRtmlCKQ" source="_WGhr0MPZEeufrKYRtmlCKQ" target="_aJ4MgMPZEeufrKYRtmlCKQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jeZE08PZEeufrKYRtmlCKQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jeZr4MPZEeufrKYRtmlCKQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jeZE0cPZEeufrKYRtmlCKQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jeZE0sPZEeufrKYRtmlCKQ" points="[-1, -15, -138, -33]$[146, -15, 9, -33]$[146, 9, 9, -9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jea6AMPZEeufrKYRtmlCKQ" id="(1.0,0.9666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jea6AcPZEeufrKYRtmlCKQ" id="(0.2,0.3)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kXX7QMPZEeufrKYRtmlCKQ" type="4001" element="_kXWtIMPZEeufrKYRtmlCKQ" source="_aJ4MgMPZEeufrKYRtmlCKQ" target="_dn-rFcPZEeufrKYRtmlCKQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_kXX7Q8PZEeufrKYRtmlCKQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kXX7RMPZEeufrKYRtmlCKQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kXX7QcPZEeufrKYRtmlCKQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kXX7QsPZEeufrKYRtmlCKQ" points="[-1, -16, -174, -28]$[175, -16, 2, -28]$[175, 5, 2, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_kXaXgMPZEeufrKYRtmlCKQ" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_kXaXgcPZEeufrKYRtmlCKQ" id="(0.43333333333333335,0.23333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lH4LIMPZEeufrKYRtmlCKQ" type="4001" element="_lH3kEMPZEeufrKYRtmlCKQ" source="_dn-rFcPZEeufrKYRtmlCKQ" target="_brycybi4EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lH4LI8PZEeufrKYRtmlCKQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lH4LJMPZEeufrKYRtmlCKQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lH4LIcPZEeufrKYRtmlCKQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lH4LIsPZEeufrKYRtmlCKQ" points="[-1, -16, -160, 117]$[65, -16, -94, 117]$[65, -121, -94, 12]$[141, -121, -18, 12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lH6AUMPZEeufrKYRtmlCKQ" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lH6AUcPZEeufrKYRtmlCKQ" id="(0.15,0.48333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_q6sZ4MR_EeuDrfIRDXGjmg" type="4001" element="_q6qksMR_EeuDrfIRDXGjmg" source="_TjN0v68zEeuSJd-ffsoCUg" target="_BO3AsMSaEeuO8sueqVfXJA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_q6sZ48R_EeuDrfIRDXGjmg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_q6sZ5MR_EeuDrfIRDXGjmg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_q6sZ4cR_EeuDrfIRDXGjmg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_q6sZ4sR_EeuDrfIRDXGjmg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rI0VcMR_EeuDrfIRDXGjmg" type="4001" element="_rIzuYMR_EeuDrfIRDXGjmg" source="_BO3AsMSaEeuO8sueqVfXJA" target="_TjN0vK8zEeuSJd-ffsoCUg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rI08gsR_EeuDrfIRDXGjmg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rI08g8R_EeuDrfIRDXGjmg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rI08gMR_EeuDrfIRDXGjmg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rI08gcR_EeuDrfIRDXGjmg" points="[0, -4, -94, 5]$[101, 21, 7, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rI3YwMR_EeuDrfIRDXGjmg" id="(0.9916666666666667,0.55)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
