<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_TjN0gK8zEeuSJd-ffsoCUg" name="FabricationBiere" author="David" bonitaVersion="7.12.1" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_TjN0ga8zEeuSJd-ffsoCUg" name="Brasserie">
      <elements xmi:type="process:Lane" xmi:id="_TjN0gq8zEeuSJd-ffsoCUg" name="Employee lane" actor="_TjN0m68zEeuSJd-ffsoCUg">
        <elements xmi:type="process:StartEvent" xmi:id="_TjN0g68zEeuSJd-ffsoCUg" name="Start" outgoing="_TjN0mK8zEeuSJd-ffsoCUg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_TjN0hK8zEeuSJd-ffsoCUg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_TjN0ha8zEeuSJd-ffsoCUg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TjN0hq8zEeuSJd-ffsoCUg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_TjN0h68zEeuSJd-ffsoCUg" name="Vérification du matériel" outgoing="_r3oj0Li5EeuOct60VCUhnQ" incoming="_TjN0mK8zEeuSJd-ffsoCUg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_TjN0iK8zEeuSJd-ffsoCUg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_TjN0ia8zEeuSJd-ffsoCUg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TjN0iq8zEeuSJd-ffsoCUg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_TjN0i68zEeuSJd-ffsoCUg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_TjN0jK8zEeuSJd-ffsoCUg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_TjN0ja8zEeuSJd-ffsoCUg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_TjN0jq8zEeuSJd-ffsoCUg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_TjN0j68zEeuSJd-ffsoCUg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_TjN0kK8zEeuSJd-ffsoCUg">
            <targetForm xmi:type="expression:Expression" xmi:id="_TjN0ka8zEeuSJd-ffsoCUg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_TjN0kq8zEeuSJd-ffsoCUg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_TjN0k68zEeuSJd-ffsoCUg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_brycwLi4EeuOct60VCUhnQ" name="Séparation des grains de malt cuits " outgoing="_wtf0oLi7EeuOct60VCUhnQ" incoming="_t66YQLi7EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_brycwri4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_brycwbi4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_brycw7i4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_brycxLi4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_brycxbi4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_brycxri4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_brycyLi4EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_brycx7i4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_2S9vsLi4EeuOct60VCUhnQ" name="Deuxième filtrage " outgoing="_4_F-wLi4EeuOct60VCUhnQ" incoming="_7ZA8ILi7EeuOct60VCUhnQ _7sHeULi7EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2S-Wwbi4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2S-WwLi4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2S-Wwri4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_2S-Ww7i4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_2S-WxLi4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_2S-Wxbi4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_2S-Wx7i4EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_2S-Wxri4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_4_C7cLi4EeuOct60VCUhnQ" name="Refroidissement du moût  " outgoing="_9mfnsLi4EeuOct60VCUhnQ" incoming="_4_F-wLi4EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4_C7cri4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4_C7cbi4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4_C7c7i4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_4_DigLi4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_4_Digbi4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4_Digri4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_4_DihLi4EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_4_Dig7i4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_9maIILi4EeuOct60VCUhnQ" name="Ajout des levures " outgoing="_FwOAgLi8EeuOct60VCUhnQ" incoming="_9mfnsLi4EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_9maIIri4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_9maIIbi4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_9maII7i4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_9maIJLi4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_9maIJbi4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_9maIJri4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_9maIKLi4EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_9maIJ7i4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_EgIZALi5EeuOct60VCUhnQ" name="Mise en bouteille " outgoing="_pp8c4Li8EeuOct60VCUhnQ" incoming="_k4Q2kLi8EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_EgJAEbi5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_EgJAELi5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_EgJAEri5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_EgJAE7i5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_EgJAFLi5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_EgJAFbi5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_EgJAF7i5EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_EgJAFri5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_OiqN4Li5EeuOct60VCUhnQ" name="Apéro" incoming="_OiufULi5EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OiqN4ri5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OiqN4bi5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_OiqN47i5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_ucH50Li5EeuOct60VCUhnQ" name="Matériel stérilisé ?" outgoing="__BIkQLi5EeuOct60VCUhnQ _NOokwLi6EeuOct60VCUhnQ" incoming="_r3oj0Li5EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_r3goAri5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_r3goAbi5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_r3goA7i5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_PsEQgLi6EeuOct60VCUhnQ" name="Stérilisation du matériel et des cuves " outgoing="_Lrn54Li6EeuOct60VCUhnQ" incoming="__BIkQLi5EeuOct60VCUhnQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pWUdori5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pWUdobi5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pWUdo7i5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pWUdpLi5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pWUdpbi5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_pWUdpri5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_pWUdqLi5EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_pWUdp7i5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_PsE3k7i6EeuOct60VCUhnQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_PsE3lLi6EeuOct60VCUhnQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_PsE3kri6EeuOct60VCUhnQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_PsE3lbi6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_scOCILi6EeuOct60VCUhnQ" name="Concassage du malt " outgoing="_3GaT8Li6EeuOct60VCUhnQ" incoming="_scSTkLi6EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_scOCIri6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_scOCIbi6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_scOCI7i6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_scOCJLi6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_scOCJbi6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_scOCJri6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_scOCKLi6EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_scOCJ7i6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_vlW9ULi6EeuOct60VCUhnQ" name="Ajout du malt dans la cuve " outgoing="_scSTkLi6EeuOct60VCUhnQ" incoming="_Lrn54Li6EeuOct60VCUhnQ _NOokwLi6EeuOct60VCUhnQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bEYegri4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bEYegbi4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bEYeg7i4EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_bEYehLi4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_bEYehbi4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_bEYehri4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_bEZFkLi4EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_bEYeh7i4EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_vlW9Wri6EeuOct60VCUhnQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_vlW9W7i6EeuOct60VCUhnQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_vlW9Wbi6EeuOct60VCUhnQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_vlXkYLi6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_3GXQoLi6EeuOct60VCUhnQ" name="Porte" outgoing="_4b45ILi6EeuOct60VCUhnQ _46cdYLi6EeuOct60VCUhnQ" incoming="_3GaT8Li6EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3GXQori6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3GXQobi6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3GXQo7i6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_4b110Li6EeuOct60VCUhnQ" name="Ajout de l'eau dans la cuve" outgoing="_H1HF4Li7EeuOct60VCUhnQ" incoming="_4b45ILi6EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4b110ri6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4b110bi6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4b1107i6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_4b111Li6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_4b111bi6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4b111ri6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_4b112Li6EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_4b1117i6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_46YL8Li6EeuOct60VCUhnQ" name="Ajout du malt concassé dans une cuve" outgoing="_GE2pMLi7EeuOct60VCUhnQ" incoming="_46cdYLi6EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_46YzAbi6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_46YzALi6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_46YzAri6EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_46YzA7i6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_46YzBLi6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_46YzBbi6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_46YzB7i6EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_46YzBri6EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_GEzl4Li7EeuOct60VCUhnQ" name="Brassage en continu" outgoing="_WiJiELi7EeuOct60VCUhnQ" incoming="_GE2pMLi7EeuOct60VCUhnQ _H1HF4Li7EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GE0M8Li7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GEzl4bi7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GE0M8bi7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_GE0M8ri7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_GE0M87i7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_GE0M9Li7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_GE0M9ri7EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_GE0M9bi7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_WiF3sLi7EeuOct60VCUhnQ" name="Premier palier : 45 degrés pendant 15 minutes " outgoing="_aKdFgLi7EeuOct60VCUhnQ" incoming="_WiJiELi7EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_WiGewbi7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_WiGewLi7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_WiGewri7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_WiGew7i7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_WiGexLi7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_WiGexbi7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_WiGex7i7EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_WiGexri7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_aKaCMLi7EeuOct60VCUhnQ" name="Deuxième palier : 60 degrés pendant 30 minutes " outgoing="_b9oTULi7EeuOct60VCUhnQ" incoming="_aKdFgLi7EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_aKaCMri7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_aKaCMbi7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_aKaCM7i7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_aKapQLi7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_aKapQbi7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_aKapQri7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_aKapRLi7EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_aKapQ7i7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_b9kB4Li7EeuOct60VCUhnQ" name="Troisième palier : 70 degrés pendant 30 minutes " outgoing="_ebW6ALi7EeuOct60VCUhnQ" incoming="_b9oTULi7EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_b9ko8bi7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_b9ko8Li7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_b9ko8ri7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_b9ko87i7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_b9ko9Li7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_b9ko9bi7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_b9ko97i7EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_b9ko9ri7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_ebSokLi7EeuOct60VCUhnQ" name="Quatrième palier : 78 degrés pendant 10 minutes " outgoing="_t66YQLi7EeuOct60VCUhnQ" incoming="_ebW6ALi7EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ebSokri7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ebSokbi7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ebSok7i7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ebSolLi7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ebSolbi7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ebSolri7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ebSomLi7EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ebSol7i7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_wtcKQLi7EeuOct60VCUhnQ" name="Porte1" outgoing="_xLBeILi7EeuOct60VCUhnQ _xwAagLi7EeuOct60VCUhnQ" incoming="_wtf0oLi7EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_wtcxUbi7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_wtcxULi7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_wtcxUri7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_xK-a0Li7EeuOct60VCUhnQ" name="Infusion/ajout du houblon amérisant " outgoing="_7sHeULi7EeuOct60VCUhnQ" incoming="_xLBeILi7EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xK-a0ri7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xK-a0bi7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xK-a07i7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_xK-a1Li7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_xK-a1bi7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xK-a1ri7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_xK-a2Li7EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_xK-a17i7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_xv9XMLi7EeuOct60VCUhnQ" name="Infusion/ajout du houblon aromatique " outgoing="_7ZA8ILi7EeuOct60VCUhnQ" incoming="_xwAagLi7EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xv9XMri7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xv9XMbi7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xv9XM7i7EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_xv9XNLi7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_xv9XNbi7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xv9XNri7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_xv9XOLi7EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_xv9XN7i7EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_FwJvELi8EeuOct60VCUhnQ" name="Brassage léger de 15 minutes " outgoing="_JtCbYLi8EeuOct60VCUhnQ" incoming="_FwOAgLi8EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_FwJvEri8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_FwJvEbi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_FwJvE7i8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_FwJvFLi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_FwJvFbi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_FwJvFri8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_FwKWILi8EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_FwJvF7i8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Js-J8Li8EeuOct60VCUhnQ" name="Fermentation haute, 15 à 20 degrés, d’une durée de 7 jours " outgoing="_SNFJ0Li8EeuOct60VCUhnQ" incoming="_JtCbYLi8EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Js-xAbi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Js-xALi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Js-xAri8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Js-xA7i8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Js-xBLi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Js-xBbi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Js-xB7i8EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Js-xBri8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_SNBfcLi8EeuOct60VCUhnQ" name="Mesure de la densité de la bière" outgoing="_V4u8MLi8EeuOct60VCUhnQ" incoming="_SNFJ0Li8EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SNBfcri8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SNBfcbi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SNBfc7i8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SNBfdLi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SNBfdbi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SNBfdri8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SNBfeLi8EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SNBfd7i8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_WdufoLi8EeuOct60VCUhnQ" name="Porte2" outgoing="_XKna0Li8EeuOct60VCUhnQ _k4Q2kLi8EeuOct60VCUhnQ" incoming="_V4u8MLi8EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_V4rR0ri8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_V4rR0bi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_V4rR07i8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndErrorEvent" xmi:id="_fG1qgLi8EeuOct60VCUhnQ" name="This is the end" incoming="_fHACkLi8EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_fG2Rkbi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_fG2RkLi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_fG2Rkri8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_pp5ZkLi8EeuOct60VCUhnQ" name="Encapsulage " outgoing="_p697cLi8EeuOct60VCUhnQ" incoming="_pp8c4Li8EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pp5Zkri8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pp5Zkbi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pp5Zk7i8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pp5ZlLi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pp5Zlbi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_pp5Zlri8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_pp5ZmLi8EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_pp5Zl7i8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_p66RELi8EeuOct60VCUhnQ" name="Etiquetage" outgoing="_vO4sILi8EeuOct60VCUhnQ" incoming="_p697cLi8EeuOct60VCUhnQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_p664Ibi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_p664ILi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_p664Iri8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_p664I7i8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_p664JLi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_p664Jbi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_p664J7i8EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_p664Jri8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_40qTkLi8EeuOct60VCUhnQ" name="Vidange de la cuve" outgoing="_fHACkLi8EeuOct60VCUhnQ" incoming="_XKna0Li8EeuOct60VCUhnQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XKk-kbi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XKk-kLi8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XKk-kri8EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_XKk-k7i8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_XKk-lLi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_XKk-lbi8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_XKk-l7i8EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_XKk-lri8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_40q6qbi8EeuOct60VCUhnQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_40q6qri8EeuOct60VCUhnQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_40q6qLi8EeuOct60VCUhnQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_40q6q7i8EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_6ZXLELi9EeuOct60VCUhnQ" name="tockage des bouteilles durant 7 jours" outgoing="_OiufULi5EeuOct60VCUhnQ" incoming="_vO4sILi8EeuOct60VCUhnQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_F_Hfgri5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_F_Hfgbi5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_F_Hfg7i5EeuOct60VCUhnQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_F_HfhLi5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_F_Hfhbi5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_F_Hfhri5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_F_HfiLi5EeuOct60VCUhnQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_F_Hfh7i5EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_6ZXLGri9EeuOct60VCUhnQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_6ZXLG7i9EeuOct60VCUhnQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_6ZXLGbi9EeuOct60VCUhnQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_6ZXLHLi9EeuOct60VCUhnQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_TjN0lK8zEeuSJd-ffsoCUg">
        <targetForm xmi:type="expression:Expression" xmi:id="_TjN0la8zEeuSJd-ffsoCUg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_TjN0lq8zEeuSJd-ffsoCUg">
        <targetForm xmi:type="expression:Expression" xmi:id="_TjN0l68zEeuSJd-ffsoCUg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_TjN0mK8zEeuSJd-ffsoCUg" target="_TjN0h68zEeuSJd-ffsoCUg" source="_TjN0g68zEeuSJd-ffsoCUg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_TjN0ma8zEeuSJd-ffsoCUg"/>
        <condition xmi:type="expression:Expression" xmi:id="_TjN0mq8zEeuSJd-ffsoCUg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4_F-wLi4EeuOct60VCUhnQ" target="_4_C7cLi4EeuOct60VCUhnQ" source="_2S9vsLi4EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4_Gl0Li4EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_4_Gl0bi4EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_9mfnsLi4EeuOct60VCUhnQ" target="_9maIILi4EeuOct60VCUhnQ" source="_4_C7cLi4EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_9mfnsbi4EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_9mfnsri4EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OiufULi5EeuOct60VCUhnQ" target="_OiqN4Li5EeuOct60VCUhnQ" source="_6ZXLELi9EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OiufUbi5EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_OiufUri5EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_r3oj0Li5EeuOct60VCUhnQ" target="_ucH50Li5EeuOct60VCUhnQ" source="_TjN0h68zEeuSJd-ffsoCUg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_r3pK4Li5EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_r3pK4bi5EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__BIkQLi5EeuOct60VCUhnQ" target="_PsEQgLi6EeuOct60VCUhnQ" source="_ucH50Li5EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__BIkQbi5EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="__BIkQri5EeuOct60VCUhnQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Lrn54Li6EeuOct60VCUhnQ" target="_vlW9ULi6EeuOct60VCUhnQ" source="_PsEQgLi6EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Lrn54bi6EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_Lrn54ri6EeuOct60VCUhnQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NOokwLi6EeuOct60VCUhnQ" target="_vlW9ULi6EeuOct60VCUhnQ" source="_ucH50Li5EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NOpL0Li6EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_NOpL0bi6EeuOct60VCUhnQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_scSTkLi6EeuOct60VCUhnQ" target="_scOCILi6EeuOct60VCUhnQ" source="_vlW9ULi6EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_scSTkbi6EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_scSTkri6EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3GaT8Li6EeuOct60VCUhnQ" target="_3GXQoLi6EeuOct60VCUhnQ" source="_scOCILi6EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3GaT8bi6EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_3GaT8ri6EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4b45ILi6EeuOct60VCUhnQ" target="_4b110Li6EeuOct60VCUhnQ" source="_3GXQoLi6EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4b45Ibi6EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_4b45Iri6EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_46cdYLi6EeuOct60VCUhnQ" target="_46YL8Li6EeuOct60VCUhnQ" source="_3GXQoLi6EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_46cdYbi6EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_46cdYri6EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GE2pMLi7EeuOct60VCUhnQ" target="_GEzl4Li7EeuOct60VCUhnQ" source="_46YL8Li6EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GE2pMbi7EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_GE2pMri7EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_H1HF4Li7EeuOct60VCUhnQ" target="_GEzl4Li7EeuOct60VCUhnQ" source="_4b110Li6EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_H1HF4bi7EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_H1HF4ri7EeuOct60VCUhnQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_WiJiELi7EeuOct60VCUhnQ" target="_WiF3sLi7EeuOct60VCUhnQ" source="_GEzl4Li7EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_WiJiEbi7EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_WiJiEri7EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_aKdFgLi7EeuOct60VCUhnQ" target="_aKaCMLi7EeuOct60VCUhnQ" source="_WiF3sLi7EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_aKdskLi7EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_aKdskbi7EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_b9oTULi7EeuOct60VCUhnQ" target="_b9kB4Li7EeuOct60VCUhnQ" source="_aKaCMLi7EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_b9oTUbi7EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_b9oTUri7EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ebW6ALi7EeuOct60VCUhnQ" target="_ebSokLi7EeuOct60VCUhnQ" source="_b9kB4Li7EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ebW6Abi7EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_ebW6Ari7EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_t66YQLi7EeuOct60VCUhnQ" target="_brycwLi4EeuOct60VCUhnQ" source="_ebSokLi7EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_t66_ULi7EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_t66_Ubi7EeuOct60VCUhnQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_wtf0oLi7EeuOct60VCUhnQ" target="_wtcKQLi7EeuOct60VCUhnQ" source="_brycwLi4EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_wtf0obi7EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_wtf0ori7EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xLBeILi7EeuOct60VCUhnQ" target="_xK-a0Li7EeuOct60VCUhnQ" source="_wtcKQLi7EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xLBeIbi7EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_xLBeIri7EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xwAagLi7EeuOct60VCUhnQ" target="_xv9XMLi7EeuOct60VCUhnQ" source="_wtcKQLi7EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xwBBkLi7EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_xwBBkbi7EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7ZA8ILi7EeuOct60VCUhnQ" target="_2S9vsLi4EeuOct60VCUhnQ" source="_xv9XMLi7EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7ZA8Ibi7EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_7ZA8Iri7EeuOct60VCUhnQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7sHeULi7EeuOct60VCUhnQ" target="_2S9vsLi4EeuOct60VCUhnQ" source="_xK-a0Li7EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7sHeUbi7EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_7sHeUri7EeuOct60VCUhnQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_FwOAgLi8EeuOct60VCUhnQ" target="_FwJvELi8EeuOct60VCUhnQ" source="_9maIILi4EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_FwOAgbi8EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_FwOAgri8EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JtCbYLi8EeuOct60VCUhnQ" target="_Js-J8Li8EeuOct60VCUhnQ" source="_FwJvELi8EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JtCbYbi8EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_JtCbYri8EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SNFJ0Li8EeuOct60VCUhnQ" target="_SNBfcLi8EeuOct60VCUhnQ" source="_Js-J8Li8EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SNFJ0bi8EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_SNFJ0ri8EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_V4u8MLi8EeuOct60VCUhnQ" target="_WdufoLi8EeuOct60VCUhnQ" source="_SNBfcLi8EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_V4u8Mbi8EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_V4u8Mri8EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XKna0Li8EeuOct60VCUhnQ" target="_40qTkLi8EeuOct60VCUhnQ" source="_WdufoLi8EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XKna0bi8EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_XKna0ri8EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_fHACkLi8EeuOct60VCUhnQ" target="_fG1qgLi8EeuOct60VCUhnQ" source="_40qTkLi8EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_fHACkbi8EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_fHACkri8EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_k4Q2kLi8EeuOct60VCUhnQ" target="_EgIZALi5EeuOct60VCUhnQ" source="_WdufoLi8EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_k4Q2kbi8EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_k4RdoLi8EeuOct60VCUhnQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_pp8c4Li8EeuOct60VCUhnQ" target="_pp5ZkLi8EeuOct60VCUhnQ" source="_EgIZALi5EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_pp8c4bi8EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_pp8c4ri8EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_p697cLi8EeuOct60VCUhnQ" target="_p66RELi8EeuOct60VCUhnQ" source="_pp5ZkLi8EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_p697cbi8EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_p6-igLi8EeuOct60VCUhnQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vO4sILi8EeuOct60VCUhnQ" target="_6ZXLELi9EeuOct60VCUhnQ" source="_p66RELi8EeuOct60VCUhnQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vO4sIbi8EeuOct60VCUhnQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_vO4sIri8EeuOct60VCUhnQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_TjN0m68zEeuSJd-ffsoCUg" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_TjN0nK8zEeuSJd-ffsoCUg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TjN0na8zEeuSJd-ffsoCUg">
        <name xmi:type="expression:Expression" xmi:id="_TjN0nq8zEeuSJd-ffsoCUg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TjN0n68zEeuSJd-ffsoCUg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TjN0oK8zEeuSJd-ffsoCUg">
        <name xmi:type="expression:Expression" xmi:id="_TjN0oa8zEeuSJd-ffsoCUg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TjN0oq8zEeuSJd-ffsoCUg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TjN0o68zEeuSJd-ffsoCUg">
        <name xmi:type="expression:Expression" xmi:id="_TjN0pK8zEeuSJd-ffsoCUg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TjN0pa8zEeuSJd-ffsoCUg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TjN0pq8zEeuSJd-ffsoCUg">
        <name xmi:type="expression:Expression" xmi:id="_TjN0p68zEeuSJd-ffsoCUg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TjN0qK8zEeuSJd-ffsoCUg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TjN0qa8zEeuSJd-ffsoCUg">
        <name xmi:type="expression:Expression" xmi:id="_TjN0qq8zEeuSJd-ffsoCUg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TjN0q68zEeuSJd-ffsoCUg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_TjN0rK8zEeuSJd-ffsoCUg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_TjN0ra8zEeuSJd-ffsoCUg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_TjN0rq8zEeuSJd-ffsoCUg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_TjN0r68zEeuSJd-ffsoCUg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_TjN0sK8zEeuSJd-ffsoCUg" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_TjN0sa8zEeuSJd-ffsoCUg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_TjN0sq8zEeuSJd-ffsoCUg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_TjN0s68zEeuSJd-ffsoCUg" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_TjN0tK8zEeuSJd-ffsoCUg" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_TjN0ta8zEeuSJd-ffsoCUg" type="Process" element="_TjN0gK8zEeuSJd-ffsoCUg" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_TjN0tq8zEeuSJd-ffsoCUg" type="2007" element="_TjN0ga8zEeuSJd-ffsoCUg">
      <children xmi:type="notation:DecorationNode" xmi:id="_TjN0t68zEeuSJd-ffsoCUg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_TjN0uK8zEeuSJd-ffsoCUg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_TjN0ua8zEeuSJd-ffsoCUg" type="3007" element="_TjN0gq8zEeuSJd-ffsoCUg">
          <children xmi:type="notation:DecorationNode" xmi:id="_TjN0uq8zEeuSJd-ffsoCUg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_TjN0u68zEeuSJd-ffsoCUg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_TjN0vK8zEeuSJd-ffsoCUg" type="3005" element="_TjN0h68zEeuSJd-ffsoCUg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_TjN0va8zEeuSJd-ffsoCUg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TjN0vq8zEeuSJd-ffsoCUg" x="118" y="53" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_TjN0v68zEeuSJd-ffsoCUg" type="3002" element="_TjN0g68zEeuSJd-ffsoCUg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_TjN0wK8zEeuSJd-ffsoCUg" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_TjN0wa8zEeuSJd-ffsoCUg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TjN0wq8zEeuSJd-ffsoCUg" x="42" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_brycybi4EeuOct60VCUhnQ" type="3027" element="_brycwLi4EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_brycy7i4EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_brycyri4EeuOct60VCUhnQ" x="2265" y="59" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2S-90Li4EeuOct60VCUhnQ" type="3027" element="_2S9vsLi4EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_2S-90ri4EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2S-90bi4EeuOct60VCUhnQ" x="2740" y="64"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4_Dihbi4EeuOct60VCUhnQ" type="3027" element="_4_C7cLi4EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4_EJkLi4EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4_Dihri4EeuOct60VCUhnQ" x="2892" y="62" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_9mb9ULi4EeuOct60VCUhnQ" type="3027" element="_9maIILi4EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_9mb9Uri4EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9mb9Ubi4EeuOct60VCUhnQ" x="3063" y="58" width="136" height="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_EgJnILi5EeuOct60VCUhnQ" type="3027" element="_EgIZALi5EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_EgJnIri5EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EgJnIbi5EeuOct60VCUhnQ" x="3952" y="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Oiq08Li5EeuOct60VCUhnQ" type="3003" element="_OiqN4Li5EeuOct60VCUhnQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Oiq08ri5EeuOct60VCUhnQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Oiq087i5EeuOct60VCUhnQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Oiq08bi5EeuOct60VCUhnQ" x="4640" y="86"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ucIg47i5EeuOct60VCUhnQ" type="3008" element="_ucH50Li5EeuOct60VCUhnQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ucIg5bi5EeuOct60VCUhnQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ucIg5ri5EeuOct60VCUhnQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ucIg5Li5EeuOct60VCUhnQ" x="327" y="61" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PsE3lri6EeuOct60VCUhnQ" type="3005" element="_PsEQgLi6EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PsE3mLi6EeuOct60VCUhnQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PsE3l7i6EeuOct60VCUhnQ" x="422" y="141" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_scOpMLi6EeuOct60VCUhnQ" type="3027" element="_scOCILi6EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_scOpMri6EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_scOpMbi6EeuOct60VCUhnQ" x="802" y="59" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vlXkYbi6EeuOct60VCUhnQ" type="3005" element="_vlW9ULi6EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_vlXkY7i6EeuOct60VCUhnQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vlXkYri6EeuOct60VCUhnQ" x="612" y="61" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_3GX3sLi6EeuOct60VCUhnQ" type="3009" element="_3GXQoLi6EeuOct60VCUhnQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_3GX3sri6EeuOct60VCUhnQ" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_3GX3s7i6EeuOct60VCUhnQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3GX3sbi6EeuOct60VCUhnQ" x="998" y="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4b2c4Li6EeuOct60VCUhnQ" type="3027" element="_4b110Li6EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4b2c4ri6EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4b2c4bi6EeuOct60VCUhnQ" x="1146" y="112" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_46ZaELi6EeuOct60VCUhnQ" type="3027" element="_46YL8Li6EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_46ZaEri6EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_46ZaEbi6EeuOct60VCUhnQ" x="1136" y="13" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_GE0M97i7EeuOct60VCUhnQ" type="3027" element="_GEzl4Li7EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_GE00ALi7EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GE0M-Li7EeuOct60VCUhnQ" x="1353" y="64"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_WiHF0Li7EeuOct60VCUhnQ" type="3027" element="_WiF3sLi7EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_WiHF0ri7EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WiHF0bi7EeuOct60VCUhnQ" x="1505" y="53" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_aKapRbi7EeuOct60VCUhnQ" type="3027" element="_aKaCMLi7EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_aKapR7i7EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_aKapRri7EeuOct60VCUhnQ" x="1695" y="54" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_b9lQALi7EeuOct60VCUhnQ" type="3027" element="_b9kB4Li7EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_b9lQAri7EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_b9lQAbi7EeuOct60VCUhnQ" x="1885" y="56" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ebTPoLi7EeuOct60VCUhnQ" type="3027" element="_ebSokLi7EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ebTPori7EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ebTPobi7EeuOct60VCUhnQ" x="2075" y="57" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_wtdYYLi7EeuOct60VCUhnQ" type="3009" element="_wtcKQLi7EeuOct60VCUhnQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_wtdYYri7EeuOct60VCUhnQ" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_wtdYY7i7EeuOct60VCUhnQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wtdYYbi7EeuOct60VCUhnQ" x="2459" y="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xK_B4Li7EeuOct60VCUhnQ" type="3027" element="_xK-a0Li7EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_xK_B4ri7EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xK_B4bi7EeuOct60VCUhnQ" x="2582" y="10" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xv9-QLi7EeuOct60VCUhnQ" type="3027" element="_xv9XMLi7EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_xv9-Qri7EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xv9-Qbi7EeuOct60VCUhnQ" x="2582" y="119" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_FwK9MLi8EeuOct60VCUhnQ" type="3027" element="_FwJvELi8EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_FwK9Mri8EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_FwK9Mbi8EeuOct60VCUhnQ" x="3260" y="62" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Js_YELi8EeuOct60VCUhnQ" type="3027" element="_Js-J8Li8EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Js_YEri8EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Js_YEbi8EeuOct60VCUhnQ" x="3454" y="64" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SNCGgLi8EeuOct60VCUhnQ" type="3027" element="_SNBfcLi8EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SNCGgri8EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SNCGgbi8EeuOct60VCUhnQ" x="3675" y="71" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_WdvGs7i8EeuOct60VCUhnQ" type="3008" element="_WdufoLi8EeuOct60VCUhnQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_WdvGtbi8EeuOct60VCUhnQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_WdvGtri8EeuOct60VCUhnQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WdvGtLi8EeuOct60VCUhnQ" x="3850" y="78" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_fG3fsLi8EeuOct60VCUhnQ" type="3050" element="_fG1qgLi8EeuOct60VCUhnQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_fG4GwLi8EeuOct60VCUhnQ" type="5052">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_fG4Gwbi8EeuOct60VCUhnQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fG3fsbi8EeuOct60VCUhnQ" x="3987" y="322"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_pp6AoLi8EeuOct60VCUhnQ" type="3027" element="_pp5ZkLi8EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pp6Aori8EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pp6Aobi8EeuOct60VCUhnQ" x="4108" y="69" width="122" height="61"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_p67fMLi8EeuOct60VCUhnQ" type="3027" element="_p66RELi8EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_p67fMri8EeuOct60VCUhnQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_p67fMbi8EeuOct60VCUhnQ" x="4279" y="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_40q6rLi8EeuOct60VCUhnQ" type="3005" element="_40qTkLi8EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_40q6rri8EeuOct60VCUhnQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_40q6rbi8EeuOct60VCUhnQ" x="3944" y="196" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6ZXyILi9EeuOct60VCUhnQ" type="3005" element="_6ZXLELi9EeuOct60VCUhnQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_6ZXyIri9EeuOct60VCUhnQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6ZXyIbi9EeuOct60VCUhnQ" x="4431" y="64" width="146" height="73"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_TjN0w68zEeuSJd-ffsoCUg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_TjN0xK8zEeuSJd-ffsoCUg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_TjN0xa8zEeuSJd-ffsoCUg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_TjN0xq8zEeuSJd-ffsoCUg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TjN0x68zEeuSJd-ffsoCUg" x="23" y="10" width="2892" height="440"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_TjN0yK8zEeuSJd-ffsoCUg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_TjN0ya8zEeuSJd-ffsoCUg" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_TjN0yq8zEeuSJd-ffsoCUg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_TjN0y68zEeuSJd-ffsoCUg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TjN0zK8zEeuSJd-ffsoCUg" width="4786" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_TjN0za8zEeuSJd-ffsoCUg"/>
    <edges xmi:type="notation:Connector" xmi:id="_TjN0zq8zEeuSJd-ffsoCUg" type="4001" element="_TjN0mK8zEeuSJd-ffsoCUg" source="_TjN0v68zEeuSJd-ffsoCUg" target="_TjN0vK8zEeuSJd-ffsoCUg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_TjN0z68zEeuSJd-ffsoCUg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_TjN00K8zEeuSJd-ffsoCUg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_TjN00a8zEeuSJd-ffsoCUg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_TjN00q8zEeuSJd-ffsoCUg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4_Gl0ri4EeuOct60VCUhnQ" type="4001" element="_4_F-wLi4EeuOct60VCUhnQ" source="_2S-90Li4EeuOct60VCUhnQ" target="_4_Dihbi4EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4_Gl1bi4EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4_Gl1ri4EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4_Gl07i4EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4_Gl1Li4EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_9mgOwLi4EeuOct60VCUhnQ" type="4001" element="_9mfnsLi4EeuOct60VCUhnQ" source="_4_Dihbi4EeuOct60VCUhnQ" target="_9mb9ULi4EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_9mgOw7i4EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_9mgOxLi4EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_9mgOwbi4EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_9mgOwri4EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OivGYLi5EeuOct60VCUhnQ" type="4001" element="_OiufULi5EeuOct60VCUhnQ" source="_6ZXyILi9EeuOct60VCUhnQ" target="_Oiq08Li5EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OivGY7i5EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OivGZLi5EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OivGYbi5EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OivGYri5EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_r3pK4ri5EeuOct60VCUhnQ" type="4001" element="_r3oj0Li5EeuOct60VCUhnQ" source="_TjN0vK8zEeuSJd-ffsoCUg" target="_ucIg47i5EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_r3px8Li5EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_r3px8bi5EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_r3pK47i5EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_r3pK5Li5EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__BLnkLi5EeuOct60VCUhnQ" type="4001" element="__BIkQLi5EeuOct60VCUhnQ" source="_ucIg47i5EeuOct60VCUhnQ" target="_PsE3lri6EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__BLnk7i5EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__BLnlLi5EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__BLnkbi5EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__BLnkri5EeuOct60VCUhnQ" points="[-2, -3, -80, -98]$[76, 95, -2, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="__BM1sLi5EeuOct60VCUhnQ" id="(0.46511627906976744,0.9767441860465116)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="__BM1sbi5EeuOct60VCUhnQ" id="(0.016666666666666666,0.55)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Lrog8Li6EeuOct60VCUhnQ" type="4001" element="_Lrn54Li6EeuOct60VCUhnQ" source="_PsE3lri6EeuOct60VCUhnQ" target="_vlXkYbi6EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Lrog87i6EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Lrog9Li6EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Lrog8bi6EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Lrog8ri6EeuOct60VCUhnQ" points="[0, 0, -168, 76]$[54, 0, -114, 76]$[54, -61, -114, 15]$[108, -61, -60, 15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_LrpIALi6EeuOct60VCUhnQ" id="(1.0,0.43333333333333335)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NOsPILi6EeuOct60VCUhnQ" type="4001" element="_NOokwLi6EeuOct60VCUhnQ" source="_ucIg47i5EeuOct60VCUhnQ" target="_vlXkYbi6EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NOs2MLi6EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NOs2Mbi6EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NOsPIbi6EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NOsPIri6EeuOct60VCUhnQ" points="[0, -10, -302, -9]$[242, -10, -60, -9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_NOtdQLi6EeuOct60VCUhnQ" id="(1.0,0.7209302325581395)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_scSTk7i6EeuOct60VCUhnQ" type="4001" element="_scSTkLi6EeuOct60VCUhnQ" source="_vlXkYbi6EeuOct60VCUhnQ" target="_scOpMLi6EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_scSTlri6EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_scSTl7i6EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_scSTlLi6EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_scSTlbi6EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3Ga7ALi6EeuOct60VCUhnQ" type="4001" element="_3GaT8Li6EeuOct60VCUhnQ" source="_scOpMLi6EeuOct60VCUhnQ" target="_3GX3sLi6EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3Ga7A7i6EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3Ga7BLi6EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3Ga7Abi6EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3Ga7Ari6EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4b45I7i6EeuOct60VCUhnQ" type="4001" element="_4b45ILi6EeuOct60VCUhnQ" source="_3GX3sLi6EeuOct60VCUhnQ" target="_4b2c4Li6EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4b5gMri6EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4b5gM7i6EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4b5gMLi6EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4b5gMbi6EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_46dEcLi6EeuOct60VCUhnQ" type="4001" element="_46cdYLi6EeuOct60VCUhnQ" source="_3GX3sLi6EeuOct60VCUhnQ" target="_46ZaELi6EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_46dEc7i6EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_46dEdLi6EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_46dEcbi6EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_46dEcri6EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GE3QQLi7EeuOct60VCUhnQ" type="4001" element="_GE2pMLi7EeuOct60VCUhnQ" source="_46ZaELi6EeuOct60VCUhnQ" target="_GE0M97i7EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_GE3QQ7i7EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_GE3QRLi7EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_GE3QQbi7EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GE3QQri7EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_H1HF47i7EeuOct60VCUhnQ" type="4001" element="_H1HF4Li7EeuOct60VCUhnQ" source="_4b2c4Li6EeuOct60VCUhnQ" target="_GE0M97i7EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_H1Hs8Li7EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_H1Hs8bi7EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_H1HF5Li7EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_H1HF5bi7EeuOct60VCUhnQ" points="[0, 0, -128, 55]$[93, -30, -35, 25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_H1IUALi7EeuOct60VCUhnQ" id="(1.0,0.48333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_WiKJILi7EeuOct60VCUhnQ" type="4001" element="_WiJiELi7EeuOct60VCUhnQ" source="_GE0M97i7EeuOct60VCUhnQ" target="_WiHF0Li7EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_WiKJI7i7EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_WiKJJLi7EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_WiKJIbi7EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WiKJIri7EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_aKdskri7EeuOct60VCUhnQ" type="4001" element="_aKdFgLi7EeuOct60VCUhnQ" source="_WiHF0Li7EeuOct60VCUhnQ" target="_aKapRbi7EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_aKdslbi7EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_aKdslri7EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_aKdsk7i7EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_aKdslLi7EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_b9o6YLi7EeuOct60VCUhnQ" type="4001" element="_b9oTULi7EeuOct60VCUhnQ" source="_aKapRbi7EeuOct60VCUhnQ" target="_b9lQALi7EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_b9o6Y7i7EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_b9o6ZLi7EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_b9o6Ybi7EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_b9o6Yri7EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ebXhELi7EeuOct60VCUhnQ" type="4001" element="_ebW6ALi7EeuOct60VCUhnQ" source="_b9lQALi7EeuOct60VCUhnQ" target="_ebTPoLi7EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ebXhE7i7EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ebXhFLi7EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ebXhEbi7EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ebXhEri7EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_t66_Uri7EeuOct60VCUhnQ" type="4001" element="_t66YQLi7EeuOct60VCUhnQ" source="_ebTPoLi7EeuOct60VCUhnQ" target="_brycybi4EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_t67mYLi7EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_t67mYbi7EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_t66_U7i7EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_t66_VLi7EeuOct60VCUhnQ" points="[0, 5, -64, 0]$[50, 3, -14, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_t680gLi7EeuOct60VCUhnQ" id="(1.0,0.44285714285714284)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_t680gbi7EeuOct60VCUhnQ" id="(0.11666666666666667,0.43333333333333335)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wtgbsLi7EeuOct60VCUhnQ" type="4001" element="_wtf0oLi7EeuOct60VCUhnQ" source="_brycybi4EeuOct60VCUhnQ" target="_wtdYYLi7EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wtgbs7i7EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wtgbtLi7EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wtgbsbi7EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wtgbsri7EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xLCFMLi7EeuOct60VCUhnQ" type="4001" element="_xLBeILi7EeuOct60VCUhnQ" source="_wtdYYLi7EeuOct60VCUhnQ" target="_xK_B4Li7EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xLCFM7i7EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xLCFNLi7EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xLCFMbi7EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xLCFMri7EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xwBBkri7EeuOct60VCUhnQ" type="4001" element="_xwAagLi7EeuOct60VCUhnQ" source="_wtdYYLi7EeuOct60VCUhnQ" target="_xv9-QLi7EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xwBooLi7EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xwBoobi7EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xwBBk7i7EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xwBBlLi7EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7ZBjMLi7EeuOct60VCUhnQ" type="4001" element="_7ZA8ILi7EeuOct60VCUhnQ" source="_xv9-QLi7EeuOct60VCUhnQ" target="_2S-90Li4EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7ZBjM7i7EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7ZBjNLi7EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7ZBjMbi7EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7ZBjMri7EeuOct60VCUhnQ" points="[0, 0, -57, 37]$[54, -35, -3, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7ZCxULi7EeuOct60VCUhnQ" id="(1.0,0.5)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7ZCxUbi7EeuOct60VCUhnQ" id="(0.19,0.96)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7sHeU7i7EeuOct60VCUhnQ" type="4001" element="_7sHeULi7EeuOct60VCUhnQ" source="_xK_B4Li7EeuOct60VCUhnQ" target="_2S-90Li4EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7sIFYLi7EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7sIFYbi7EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7sHeVLi7EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7sHeVbi7EeuOct60VCUhnQ" points="[0, 0, -64, -30]$[45, 19, -19, -11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7sIscLi7EeuOct60VCUhnQ" id="(1.0,0.5833333333333334)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7sIscbi7EeuOct60VCUhnQ" id="(0.26,0.22)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_FwOAg7i8EeuOct60VCUhnQ" type="4001" element="_FwOAgLi8EeuOct60VCUhnQ" source="_9mb9ULi4EeuOct60VCUhnQ" target="_FwK9MLi8EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_FwOnkLi8EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_FwOnkbi8EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_FwOAhLi8EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_FwOAhbi8EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JtCbY7i8EeuOct60VCUhnQ" type="4001" element="_JtCbYLi8EeuOct60VCUhnQ" source="_FwK9MLi8EeuOct60VCUhnQ" target="_Js_YELi8EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JtCbZri8EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JtCbZ7i8EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JtCbZLi8EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JtCbZbi8EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SNFJ07i8EeuOct60VCUhnQ" type="4001" element="_SNFJ0Li8EeuOct60VCUhnQ" source="_Js_YELi8EeuOct60VCUhnQ" target="_SNCGgLi8EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_SNFJ1ri8EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SNFJ17i8EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SNFJ1Li8EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SNFJ1bi8EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_V4vjQLi8EeuOct60VCUhnQ" type="4001" element="_V4u8MLi8EeuOct60VCUhnQ" source="_SNCGgLi8EeuOct60VCUhnQ" target="_WdvGs7i8EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_V4vjQ7i8EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_V4vjRLi8EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_V4vjQbi8EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_V4vjQri8EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XKoB4Li8EeuOct60VCUhnQ" type="4001" element="_XKna0Li8EeuOct60VCUhnQ" source="_WdvGs7i8EeuOct60VCUhnQ" target="_40q6rLi8EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XKoB47i8EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XKoB5Li8EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XKoB4bi8EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XKoB4ri8EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_fHApoLi8EeuOct60VCUhnQ" type="4001" element="_fHACkLi8EeuOct60VCUhnQ" source="_40q6rLi8EeuOct60VCUhnQ" target="_fG3fsLi8EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_fHApo7i8EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_fHAppLi8EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_fHApobi8EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_fHApori8EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_k4VvELi8EeuOct60VCUhnQ" type="4001" element="_k4Q2kLi8EeuOct60VCUhnQ" source="_WdvGs7i8EeuOct60VCUhnQ" target="_EgJnILi5EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_k4VvE7i8EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_k4VvFLi8EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_k4VvEbi8EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_k4VvEri8EeuOct60VCUhnQ" points="[-2, -8, -118, 0]$[94, -3, -22, 5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_k4XkQLi8EeuOct60VCUhnQ" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_k4XkQbi8EeuOct60VCUhnQ" id="(0.22,0.64)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_pp8c47i8EeuOct60VCUhnQ" type="4001" element="_pp8c4Li8EeuOct60VCUhnQ" source="_EgJnILi5EeuOct60VCUhnQ" target="_pp6AoLi8EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pp8c5ri8EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pp8c57i8EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pp8c5Li8EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_pp8c5bi8EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_p6-igbi8EeuOct60VCUhnQ" type="4001" element="_p697cLi8EeuOct60VCUhnQ" source="_pp6AoLi8EeuOct60VCUhnQ" target="_p67fMLi8EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_p6-ihLi8EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_p6-ihbi8EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_p6-igri8EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_p6-ig7i8EeuOct60VCUhnQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vO4sI7i8EeuOct60VCUhnQ" type="4001" element="_vO4sILi8EeuOct60VCUhnQ" source="_p67fMLi8EeuOct60VCUhnQ" target="_6ZXyILi9EeuOct60VCUhnQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vO5TMLi8EeuOct60VCUhnQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vO5TMbi8EeuOct60VCUhnQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vO4sJLi8EeuOct60VCUhnQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vO4sJbi8EeuOct60VCUhnQ" points="[0, 4, -73, 0]$[52, 6, -21, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vO56QLi8EeuOct60VCUhnQ" id="(1.0,0.54)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vO56Qbi8EeuOct60VCUhnQ" id="(0.175,0.5666666666666667)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
